### ISSUE TITLE
devel_glfw3.1: remaining parts for exposure

### ISSUE THREAD

**Issue by emidoots** [go-gl/glfw#104]
We're currently in a somewhat-awkward state where we haven't exposed all of GLFW 3.1 functionality, and it's not clear what hasn't yet been exposed. If it's okay with you all, lets keep this list here so we know need what needs to be exposed still.

We can check-off items as we add them to the 3.1 branch. These are just copied from the GLFW change log (I cut out the ones we already have):
- [x] Added `GLFWcursor` custom system cursor handle
- [x] Added `glfwCreateCursor`, `glfwDestroyCursor` and `glfwSetCursor` for
  managing custom system cursors
- [x] Added `GLFWimage` struct for passing 32-bit RGBA images
- [x] Added `glfwGetWindowFrameSize` for retrieving the size of the frame around
  the client area of a window
- [x] Added `GLFW_DONT_CARE` for indicating that any value is acceptable
- [x] Added `GLFW_DOUBLEBUFFER` for controlling whether to use double buffering
- [x] Added `GLFW_CONTEXT_RELEASE_BEHAVIOR` and values
  `GLFW_ANY_RELEASE_BEHAVIOR`, `GLFW_RELEASE_BEHAVIOR_FLUSH` and
  `GLFW_RELEASE_BEHAVIOR_NONE` for `GL_KHR_context_flush_control` support

**Comment by tapir** [comment]
Working on wrapping cursor related things

**Comment by tapir** [comment]
Working on other stuff as well. Letting you know just to avoid double work

**Comment by tapir** [comment]
Done. Any other new features to implement?

**Comment by emidoots** [comment]
Looking at the [changelog](https://github.com/glfw/glfw#changelog) I don't see anything else being added.

I'm going to close this, but if someone finds something else feel free to re-open this issue.
