### ISSUE TITLE
Instructions in README seem only partially correct.

### ISSUE THREAD

**Issue by davemackintosh** [go-gl/glfw#109]
I tried to follow the instructions in the readme but for some reason go could not find the installation of GLFW and wouldn't build.

In order to get it to work I had to flag where the include/lib was. The same with `go-gl` seems like the issue is with my local version of go but I just followed the instructions.

``` bash
CGO_CFLAGS="-I/usr/local/include" CGO_LDFLAGS="-L/usr/local/lib/" go get github.com/go-gl/glfw3
```

go version go1.4 darwin/amd64
OSx 10.10.1 (14B25)

**Comment by tapir** [comment]
normally you should install glfw to /usr not /usr/local. the readme is not
about how to compile and install glfw so I'm not sure if this should be
there but what you have to do is to tell cmake to use /usr as the prefix

**Comment by davemackintosh** [comment]
I didn't change any paths, just ran the 4 commands in the readme (I'm lazy) and ended up having to do a workaround.

**Comment by dmitshur** [comment]
Using `/usr/local/` for GLFW on OS X is normal. I've used these steps to successfully install `glfw3` on OS X, can you check if this works for you? As you can see, I didn't need to change `CGO_*FLAGS`.

https://github.com/shurcooL/reusable-commands/blob/b2f80a241ce5422a9670d302d65c704df4fbedab/go-gl_glfw3_install.sh#L1-L18
