### ISSUE TITLE
devel_glfw3.1: too many errors

### ISSUE THREAD

**Issue by emidoots** [go-gl/glfw#118]
@tapir [said](https://github.com/go-gl/glfw3/pull/113):

> The thing is now all the functions return an error and most of the errors are actually panics.
> Looks a bit overdone. Ideas?

**Comment by emidoots** [comment]
This has been the case since we moved to returning errors instead of using a callback to handle them.

GLFW doesn't yet document which functions can return which errors (see https://github.com/glfw/glfw/issues/361), so we have no way of knowing what function can cause what errors.

I don't think there is a good solution, really.

**Comment by tapir** [comment]
I agree with the original reasoning of returning errors from all functions.
Right now returning errors only matters when only one of these errors occur.

```
APIUnavailable
VersionUnavailable
FormatUnavailable
```

My question is, are these errors specific enough to connect them to specific functions. If not let's just keep going with the current solution. But if we're talking about only couple of functions then maybe we should think about it more.

**Comment by tapir** [comment]
Just as a more thinking fuel, now instead of this

``` go
for !window.ShouldClose() {
        // Do OpenGL stuff
        window.SwapBuffers()
        glfw.PollEvents()
}
```

we have to do something like this

``` go
for isFinished := false; !isFinished; isFinished, _ = window.ShouldClose() {
        // Do OpenGL stuff
        window.SwapBuffers()
        glfw.PollEvents()
 }
```

It's not really too bad. I just want to make sure we cover everything before we're stuck with it.

**Comment by pwaller** [comment]
Uh, isn't that for loop buggy? Don't you have to also check the error return value of `ShouldClose`? I'm just wondering what happens if `ShouldClose` returns `false, Error(BAD THING)`. Then `isFinished` will never be true..

**Comment by tapir** [comment]
@pwaller yes it is. doesn't change the point though. the API is slightly more bothering now since we return errors from all functions.

**Comment by dmitshur** [comment]
In my personal code, I've been doing:

``` Go
for !mustBool(window.ShouldClose()) {
    // Do OpenGL stuff
    window.SwapBuffers()
    glfw.PollEvents()
}

func mustBool(b bool, err error) bool {
    if err != nil {
        panic(err)
    }
    return b
}
```

Just pointing it out, not suggesting anything. I am still thinking about the best course of action here.

**Comment by emidoots** [comment]
I'm working out right now which functions return those errors, exactly.

**Comment by emidoots** [comment]
I've determined **_exactly_** which functions can generate which (non-panic) errors by `grep`ing through the source for uses and then tracing them back up the call stack to the public GLFW C function. These are:

| Error | Generated by function(s) |
| --- | --- |
| `GLFW_API_UNAVAILABLE` | `glfwCreateWindow` `glfwInit` `glfwIconifyWindow` `glfwRestoreWindow` |
| `GLFW_VERSION_UNAVAILABLE` | `glfwCreateWindow` |
| `GLFW_FORMAT_UNAVAILABLE` | `glfwGetClipboardString` |

All other errors are translated to panics after #112.

After the pending PR's on `devel_glfw3.1` are closed I will send one to remove the returned error from each function aside from the ones mentioned above.

**Comment by tapir** [comment]
I'm going to challenge this issue a little bit more. Please don't think I'm against it, I just want to do it correctly the first time since this breaks compatibility :)

Why do we think rest of the errors are unrecoverable? What if an application tries to create a GLFW window, receives and error and switches to commandline interface or something?

Right now the application will terminate assuming that the error is unrecoverable. Is it really?

**Comment by emidoots** [comment]
@tapir: Can you elaborate a bit more on what you're talking about? I think I might not understand correctly.

If you're talking about the other error codes:

```
    notInitialized   ErrorCode = C.GLFW_NOT_INITIALIZED    // GLFW has not been initialized.
    noCurrentContext ErrorCode = C.GLFW_NO_CURRENT_CONTEXT // No context is current.
    invalidEnum      ErrorCode = C.GLFW_INVALID_ENUM       // One of the enum parameters for the function was given an invalid enum.
    invalidValue     ErrorCode = C.GLFW_INVALID_VALUE      // One of the parameters for the function was given an invalid value.
    outOfMemory      ErrorCode = C.GLFW_OUT_OF_MEMORY      // A memory allocation failed.
    platformError    ErrorCode = C.GLFW_PLATFORM_ERROR     // A platform-specific error occurred that does not match any of the more specific categories.
```

Each one of those is a panic, yes. If you review the [analysis doc](http://www.glfw.org/docs/latest/group__errors.html) you'll find the description of each one almost perfectly matches that of a panic: each one is a _programmer error_.

**Comment by tapir** [comment]
Yeah you're right. We can panic on programmer errors. Didn't think it through.

> by greping through the source for uses and then tracing them back up the call stack to the public GLFW C function.

can you make a script for that, for future use?

**Comment by emidoots** [comment]
> can you make a script for that, for future use?

It was all done by hand/manually in my text editor via it's basic search functionality after finding the error codes via `grep`. I don't know how I could script that together without writing e.g. a C parser, honestly.

**Comment by pwaller** [comment]
@shurcooL, I love the mustBool pattern :grin:
