### ISSUE TITLE
GLFW 3.1.1

### ISSUE THREAD

**Issue by emidoots** [go-gl/glfw#132]
We should look into changing `go-gl/glfw/v3.1` to be v3.1.1 or something. It was released recently and adds a workaround for a critical bug that renders GLFW useless on most Linux window managers in the wild today.

@shurcooL any thoughts regarding this?

**Comment by tapir** [comment]
Is it really necessary? I think we can live without bug fix versioning. I would say 3.1.x is good enough.

**Comment by dmitshur** [comment]
I think @slimsag meant updating `github.com/go-gl/glfw/v3.1/glfw` from v3.1.0 to v3.1.1. The import is not changing, we're just updating the GLFW C library version.

Yes, we should. These Go bindings target the latest stable official release of GLFW. It's just a matter of doing https://github.com/go-gl/glfw/wiki/Development#updating-glfw-c-source steps.
