### ISSUE TITLE
Native Darwin Support

### ISSUE THREAD

**Issue by tapir** [go-gl/glfw#136]
Due to a bug in cgo we commented out https://github.com/go-gl/glfw/blob/master/v3.1/glfw/native_darwin.go (See Issue #82)

Unfortunately I don't have a mac, can we test if this is still an issue?

**Comment by dmitshur** [comment]
I can test this.

**Comment by dmitshur** [comment]
Uncommenting those 2 funcs, I still get:

```
glfw $ go version
go version go1.4.2 darwin/amd64
glfw $ go build
# github.com/go-gl/glfw/v3.1/glfw
./native_darwin.go:12:9: struct size calculation error off=8 bytesize=0
```

**Comment by dmitshur** [comment]
https://github.com/golang/go/issues/7555 is still not resolved.

**Comment by dmitshur** [comment]
golang/go#7555 is now closed, so this might be fixed in Go 1.5. I'll try again then, unless someone can test it sooner.

**Comment by dmitshur** [comment]
Well, this doesn't look good. Despite golang/go#7555 being resolved by now, it doesn't appear to fix this issue. I just tried with go1.5beta3.

```
$ go install github.com/go-gl/glfw/v3.1/glfw
# github.com/go-gl/glfw/v3.1/glfw
github.com/go-gl/glfw/v3.1/glfw/native_darwin.go:10:9: struct size calculation error off=8 bytesize=0
$ go version
go version go1.5beta3 darwin/amd64
```

@slimsag, we should make sure that this issue is indeed related to golang/go#7555 and not something else. Does it mean golang/go#7555 is not truly resolved? If so, there's little time before 1.5 comes out, so this may end up being postponed to Go 1.6 which is 6+ months down the line. Luckily, this issue is not very critical, but it will be nice to resolve it eventually.

**Comment by dmitshur** [comment]
It's surprising that the GLFW v3.0 bindings have nearly the same code in the `github.com/go-gl/glfw/v3.0/glfw/native_darwin.go` file and yet that seems to compile okay. What makes v3.1 different?

**Comment by dmitshur** [comment]
Well, after looking into details of golang/go#7555 and the messages that pointed to it, I realize it's a completely unrelated issue to this problem.

golang/go#7555 was referred to by @slimsag in response to https://github.com/go-gl/glfw/issues/82#issuecomment-53859967, which mentions an `undefined: strdup` error.

This `struct size calculation error` is unrelated to golang/go#7555 so it's no wonder that issue being resolved did not fix this issue.

**Comment by tapir** [comment]
On a side note, since golang/go#7555 is now closed can we revert back #87 once 1.5 is out?

**Comment by dmitshur** [comment]
Sure, but please make a separate issue for that.

I'll try to make a small reproducible sample for this `struct size calculation error` so we can create a specific Go issue if needed.

**Comment by dmitshur** [comment]
This issue _might_ be related to https://github.com/golang/go/issues/3505 which is still unresolved.

All [other issues that contain that error message](https://github.com/golang/go/search?utf8=%E2%9C%93&q=%22struct+size+calculation+error%22&type=Issues) appear to be resolved.

**Comment by dmitshur** [comment]
Here's a really short reproduce case:

``` Go
// +build darwin

package main

/*
#cgo CFLAGS: -x objective-c

id foo() {
    return 0;
}
*/
import "C"

import "fmt"

func main() {
    fmt.Println(C.foo())
}
```

Building that results in:

```
./main.go:17:14: struct size calculation error off=8 bytesize=0
```

**Comment by tapir** [comment]
A lot of the cgo libraries out there should fail to compile if this is
really the case. Are you opening an issue in golang ?

**Comment by emidoots** [comment]
Nice job tracking this down @shurcooL! Apologies for not being very responsive here prior.

I tried looking into it a bit now but it is hard to tell if it's related to golang/go#3505 or not. I agree with @tapir about opening a new issue for it so it is not overlooked.

**Comment by dmitshur** [comment]
I've filed a new issue with all the details at https://github.com/golang/go/issues/12065.

**Comment by tapir** [comment]
Looks like the problem lies within LLVM

**Comment by james4k** [comment]
Can we return a `uintptr` instead? What do you gain from using C.id in the exported API?

**Comment by dmitshur** [comment]
That could work. I think `C.id` was used because that's the type that the C API returns.

Have you tried it with `uintptr`?

**Comment by james4k** [comment]
Using cgo types in an exported API is a little weird since AFAIK cgo types in each package are distinct. `C.id` from a package that may use this API is a different type from glfw's `C.id`.

**Comment by tapir** [comment]
I'm ok with using a reference to it instead of the actual C type.

**Comment by dmitshur** [comment]
@james4k, would you be able to make a PR that resolves this issue?

**Comment by james4k** [comment]
Sure. What I ended up needing to do was a little more involved, where the conversion is done on the C side with a wrapper inline function that returns `void *`.

**Comment by emidoots** [comment]
James, that sounds correct. Not sure how else it could be worked around.

**Comment by Zijun-Yin** [comment]
> Due to a bug in cgo we commented out https://github.com/go-gl/glfw/blob/master/v3.1/glfw/native_darwin.go (See Issue #82)
> 
> Unfortunately I don't have a mac, can we test if this is still an issue?

When I ues fyne on MacOS12 with gcc11, I found it a bug which make fyne bad!
```
# github.com/go-gl/glfw/v3.3/glfw
In file included from /Users/pro/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211024062804-40e447a793be/native_darwin.go:7:
In file included from ./glfw/include/GLFW/glfw3native.h:95:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:12:
```
