### ISSUE TITLE
Weird OpenGL Context switch Behaviour because of glfw.WaitEvents()

### ISSUE THREAD

**Issue by mbertschler** [go-gl/glfw#143]
I am trying to write a multithreaded App with GLFW 3.1 and OpenGL 2.1 and ran into a bug that is driving me crazy for hours already.

For the multithreaded stuff I am following this example: https://github.com/golang/go/wiki/LockOSThread
I adapted the main loop from a range over `mainfunc` into a select loop with the default case being `glfw.WaitEvents()` because of course I want to handle events too. Because `WaitEvents` is blocking I made the `mainfunc` channel buffered, and in `do()` I added `glfw.PostEmptyEvent()` that `WaitEvents` returns and the function I am sending gets run. 

Everything works great, except that only one of the three windows gets rendered. The event callbacks, in this case the scroll callback works.
<img width="400" alt="screen shot 2015-08-13 at 17 43 22" src="https://cloud.githubusercontent.com/assets/3779568/9254395/89382f1c-41e3-11e5-9ad1-53298e8053db.png">

I can get the other two windows to render if i comment out the `default: glfw.WaitEvents()` part in my `Main()` loop. But then of course I can't catch events anymore.
<img width="400" alt="screen shot 2015-08-13 at 17 43 53" src="https://cloud.githubusercontent.com/assets/3779568/9254394/893603ea-41e3-11e5-87aa-444f4b23cca9.png">

Has anyone ever done that before or am I doing something terribly wrong?

I am on `go version go1.4.2 darwin/amd64`

The code is also here: https://gist.github.com/mbertschler/426362db4a2cd70e316b

``` go
package main

import (
    "fmt"
    "runtime"
    "time"

    "github.com/go-gl/gl/v2.1/gl"
    "github.com/go-gl/glfw/v3.1/glfw"
)

func main() {
    runtime.LockOSThread()
    if err := glfw.Init(); err != nil {
        panic(err)
    }
    glfw.WindowHint(glfw.ContextVersionMajor, 2)
    glfw.WindowHint(glfw.ContextVersionMinor, 1)
    glfw.WindowHint(glfw.Samples, 4)
    if err := gl.Init(); err != nil {
        panic(err)
    }
    // do stuff outside of main goroutine
    go doStuff()

    // run the mainthread loop
    Main()
}

// outside the mainthread goroutine
func doStuff() {
    Window1 := NewWindow("Window 1", 400, 300)
    Window1.Render()

    Window2 := NewWindow("Window 2", 300, 200)
    Window2.Render()

    time.Sleep(time.Second)
    Window3 := NewWindow("Window 3", 200, 100)
    Window3.Render()
}

// ================== main thread ====================
// adapted from: https://github.com/golang/go/wiki/LockOSThread

func Main() {
    // original code:
    // for f := range mainfunc {
    //  f()
    // }

    // select loop to catch events:
    for {
        select {
        case f := <-mainfunc:
            f()

            //comment out these two lines:
        default:
            glfw.WaitEvents()

        }
    }
}

// buffered channel to make it possible to put a func
// in the chan and then run it with PostEmptyEvent()
var mainfunc = make(chan func(), 1)

func do(f func()) {
    done := make(chan bool, 1)
    mainfunc <- func() {
        f()
        done <- true
    }

    // added to break WaitEvents in Main():
    glfw.PostEmptyEvent()

    <-done
}

// ================= Window functions =================

type Window struct {
    win *glfw.Window
}

func NewWindow(title string, width, height int) *Window {
    var win *glfw.Window
    var err error
    do(func() {
        win, err = glfw.CreateWindow(width, height, title, nil, nil)
        if err != nil {
            panic(err)
        }
        win.MakeContextCurrent()
        win.SetScrollCallback(func(w *glfw.Window, xoff float64, yoff float64) {
            fmt.Printf("Scroll: x: %.1f y: %.1f\n", xoff, yoff)
        })
        gl.ClearColor(0.2, 0.2, 0.2, 1.0)
    })
    return &Window{win}
}

func (w *Window) Render() {
    do(func() {
        w.win.MakeContextCurrent()
        gl.Clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT)
        w.win.SwapBuffers()
    })
}
```

**Comment by mbertschler** [comment]
Okay so I think I can see what is going on here. Here is what I found:

## The Fake Fix

#### With this Window 2 and 3 stay black:

``` go
func doStuff() {
    Window1 := NewWindow("Window 1", 400, 300)
    Window1.Render()

    Window2 := NewWindow("Window 2", 300, 200)
    Window2.Render()
    Window2.Render()

    Window3 := NewWindow("Window 3", 200, 100)
    Window3.Render()
    Window3.Render()
}
```

#### With this only Window 3 stays black:

``` go
func doStuff() {
    Window1 := NewWindow("Window 1", 400, 300)
    Window1.Render()

    Window2 := NewWindow("Window 2", 300, 200)
    Window2.Render()

    Window3 := NewWindow("Window 3", 200, 100)
    Window3.Render()
    Window3.Render()
    Window2.Render()
}
```

#### With this all 3 window are grey:

``` go
func doStuff() {
    Window1 := NewWindow("Window 1", 400, 300)
    Window1.Render()

    Window2 := NewWindow("Window 2", 300, 200)
    Window2.Render()

    Window3 := NewWindow("Window 3", 200, 100)
    Window3.Render()
    Window2.Render()
    Window3.Render()
}
```

## The Problem

This means that something weird is going on while switching OpenGL contexts between windows, but only if `glfw.WaitEvents()` is called. 

With my `doStuff()` function like that:

``` go
func doStuff() {
    Window1 := NewWindow("Window 1", 400, 300)
    Window1.Render()

    Window2 := NewWindow("Window 2", 300, 200)
    Window2.Render()

    Window3 := NewWindow("Window 3", 200, 100)
    Window3.Render()
}
```

I can add the 2 lines for clearing and buffer swapping at the end of the creation function:

``` go
func NewWindow(title string, width, height int) *Window {
    var win *glfw.Window
    var err error
    do(func() {
        win, err = glfw.CreateWindow(width, height, title, nil, nil)
        if err != nil {
            panic(err)
        }
        win.MakeContextCurrent()
        win.SetScrollCallback(func(w *glfw.Window, xoff float64, yoff float64) {
            fmt.Printf("Scroll: x: %.1f y: %.1f\n", xoff, yoff)
        })
        gl.ClearColor(0.2, 0.2, 0.2, 1.0)

        // Added these 2 lines:
        gl.Clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT)
        win.SwapBuffers()
    })
    return &Window{win, title}
}
```

And all 3 windows are rendered grey. This means that the context is only switched between the 2 `do()` calls for creating and rendering the window. I added debug prints to the main loop, and saw that `WaitEvents()` is called once between `do()` functions. To make sure that `WaitEvents()` doesn't change the context I did this.

``` go
default:
    before := glfw.GetCurrentContext()
    glfw.WaitEvents()
    after := glfw.GetCurrentContext()
    if before != after {
        fmt.Println("Context changed!")
    }
```

It never did anything, so the context in the library is not changed, but the problem must be a layer deeper.

## The Fix

With all this information I was able to find a fix for this problem. The context needs to be detatched at the end of the creation function or at the beginning of the render function using `glfw.DetachCurrentContext()`.

#### Either fix here:

``` go
func NewWindow(title string, width, height int) *Window {
    var win *glfw.Window
    var err error
    do(func() {
        win, err = glfw.CreateWindow(width, height, title, nil, nil)
        if err != nil {
            panic(err)
        }
        win.MakeContextCurrent()
        win.SetScrollCallback(func(w *glfw.Window, xoff float64, yoff float64) {
            fmt.Printf("Scroll: x: %.1f y: %.1f\n", xoff, yoff)
        })
        gl.ClearColor(0.2, 0.2, 0.2, 1.0)

        // FIX:
        glfw.DetachCurrentContext()

    })
    return &Window{win, title}
}
```

#### Or fix here:

``` go
func (w *Window) Render() {
    do(func() {

        // FIX:
        glfw.DetachCurrentContext()

        w.win.MakeContextCurrent()
        gl.Clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT)
        w.win.SwapBuffers()
    })
}
```

## Conclusion

Okay so now that I found out how to fix this problem: Are `MakeContextCurrent()` calls not enough and can lead to this weird behaviour, see "Fake Fix" and is `DetachCurrentContext()` required before making a new context current?

Either the docs should mention this or this is actually a GLFW bug. I hope this monsterpost helps either way :wink:

**Comment by dmitshur** [comment]
Hi @mbertschler,

Sorry for not replying sooner.

That definitely looks strange, especially the fix you found. I would not expect that fix to have any effect.

As far as I know, doing `DetachCurrentContext` is equivalent to making "no context" current. But setting another context as current will basically override that.

Unless I'm missing something, detaching current context before immediately setting another context current should never have any effect. @elmindreda does that sound right to do you? Or is it normal for detaching a current context having some effect when immediately followed by setting another context current?

If it's not expected to have any effect as I think, then this is possibly a bug either in `v3.1/glfw` Go bindings or in GLFW (C library).

**Comment by elmindreda** [comment]
@shurcooL Yes, that shouldn't matter. See the `windows` GLFW example, which does something similar to this.

**Comment by elmindreda** [comment]
It sounds vaguely related to glfw/glfw#500, if only because NSOpenGLView is a big ball of broken DWIM.

**Comment by mbertschler** [comment]
I have a reduced example for reproducing that bug. It has nothing to do with calling things from different goroutines. It doesn't matter if I use `WaitEvents()` or `PollEvents()`, both calls cause this bug. If you comment out the two troublemaker lines things are working properly. I added the different possibilities to work around that problem.

``` go
package main

import (
    "fmt"
    "runtime"

    "github.com/go-gl/gl/v2.1/gl"
    "github.com/go-gl/glfw/v3.1/glfw"
)

func main() {
    runtime.LockOSThread()
    if err := glfw.Init(); err != nil {
        panic(err)
    }
    glfw.WindowHint(glfw.ContextVersionMajor, 2)
    glfw.WindowHint(glfw.ContextVersionMinor, 1)
    glfw.WindowHint(glfw.Samples, 4)
    if err := gl.Init(); err != nil {
        panic(err)
    }

    glfw.PollEvents()
    Window1 := NewWindow("Window 1", 400, 300, 0.2)
    glfw.PollEvents()
    Window1.Render()

    glfw.PollEvents()
    Window2 := NewWindow("Window 2", 300, 200, 0.4)
    // Troublemaker 1:
    // causes Window2 to be black
    glfw.PollEvents()
    Window2.Render()

    glfw.PollEvents()
    Window3 := NewWindow("Window 3", 200, 100, 0.6)
    // Troublemaker 2:
    // causes Window3 to be black
    glfw.PollEvents()
    Window3.Render()

    // FIX a:
    // Window2.Render()
    // Window3.Render()

    for {
        glfw.WaitEvents()
    }
}

type Window struct {
    win   *glfw.Window
    Title string
}

func NewWindow(title string, width, height int, col float32) *Window {
    win, err := glfw.CreateWindow(width, height, title, nil, nil)
    if err != nil {
        panic(err)
    }
    win.MakeContextCurrent()
    win.SetScrollCallback(func(w *glfw.Window, xoff float64, yoff float64) {
        fmt.Printf("Scroll: x: %.1f y: %.1f\n", xoff, yoff)
    })
    gl.ClearColor(col, col, col, 1.0)

    // FIX b:
    // glfw.DetachCurrentContext()

    return &Window{win, title}
}

func (w *Window) Render() {
    // FIX c:
    // glfw.DetachCurrentContext()

    w.win.MakeContextCurrent()
    gl.Clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT)
    w.win.SwapBuffers()
}
```

**Comment by elmindreda** [comment]
Here is a [straight port to C](https://gist.github.com/elmindreda/6def409edbc5cc924a59).

Bisect identifies glfw/glfw@a21f586c3b36ccf452ea06582005d897f98c3ec6, which fixes a symptom caused by the actual issue of NSOpenGLView DWIM properly fixed by glfw/glfw@8f0fd7ecf5970221fc7b915d8826521b5eb89ef7. Both of these fixes are in what will be 3.1.2.

**Comment by dmitshur** [comment]
Great to hear, thanks for looking into this!

**Comment by mbertschler** [comment]
@elmindreda I'm glad that this will soon be fixed. Thank you for looking into that! @shurcooL Should we close this when the GLFW version of the binding will be bumped to 3.1.2 or now?

**Comment by dmitshur** [comment]
Since this issue is completely on the GLFW (C library) side and there's nothing actionable (specific to this issue) to do on the Go binding side, we can close this issue.

As soon as GLFW 3.1.2 is released, I'll be sure to update the Go bindings to use it.

Thank you @mbertschler and @elmindreda for reporting, investigating and getting to the bottom of it!
