### ISSUE TITLE
Are there plans for 64-bit support

### ISSUE THREAD

**Issue by kd7tck** [go-gl/glfw#152]
Does not seem to compile on my 64 bit golang 1.5 compiler.

**Comment by ghost** [comment]
Can you show us your stack trace. I have no issue on darwin/amd64 and linux/amd64

**Comment by dmitshur** [comment]
What's the error from the compiler? What does `go version` print? What OS are you running?

**Comment by kd7tck** [comment]
go version is go1.5.1 windows/amd64
My OS is windows 10. The error is "cc1.exe: sorry, unimplemented: 64-bit mode not compiled in"

[go test trace/go tool trace] is not outputting any files for some reason.

**Comment by tapir** [comment]
and what about gcc version? looks like you're on 32-bit gcc.

**Comment by kd7tck** [comment]
I use TDM64. Is there some setting I should check inside of go to ensure it uses the 64 bit version of gcc? I know that the dragon compiler includes both 32 and 64 bit versions of gcc.

**Comment by tapir** [comment]
No idea. I use MSYS2 (http://msys2.github.io/) and highly recommend it. It creates shell links for 32-bit and 64-bit. It also has a package manager (pacman).
