### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by fcvarela** [go-gl/glfw#154]
Are there any plans to add Vulcan support, now that GLFW has it? Or would this fall outside the go-gl umbrella?

**Comment by tapir** [comment]
It will support Vulkan. I've pushed a "devel" branch yesterday for GLFW 3.2. Keep an eye on that for updates.

**Comment by fcvarela** [comment]
Awesome, thanks, sorry I missed it!

**Comment by tapir** [comment]
:+1:

**Comment by xlab** [comment]
Hi! Sorry for reviving an old question, but I can't find methods related to Vulkan API support, like this one:
http://www.glfw.org/docs/latest/group__vulkan.html#ga1a24536bec3f80b08ead18e28e6ae965

``` c
VkResult glfwCreateWindowSurface    (   VkInstance  instance,
GLFWwindow *    window,
const VkAllocationCallbacks *   allocator,
VkSurfaceKHR *  surface 
)   
```
