### ISSUE TITLE
Example makes Chrome incredibly slow on rendering

### ISSUE THREAD

**Issue by lzap** [go-gl/glfw#155]
Not sure what happened, but I am using Fedora 22 with i3 wm and after I tried to run the example code from the README, I could not exit it (as i3 wm does not have an exit button) and the key combination did not work. I had to xkill the app, but this made Chrome incredibly slow (it worked but very slow like scrolling or tab changing). I am not sure what happened. Maybe to add an exit on esc bit to close OpenGL context properly?

**Comment by lzap** [comment]
I understand you guys will perhaps want to stick with glfw example but just in case

``` Go
package main

import (
    "github.com/go-gl/glfw/v3.1/glfw"
    "runtime"
)

func init() {
    // This is needed to arrange that main() runs on main thread.
    // See documentation for functions that are only allowed to be called from the main thread.
    runtime.LockOSThread()
}

func key_events(win *glfw.Window, key glfw.Key, scancode int, action glfw.Action, mods glfw.ModifierKey) {
    if key == glfw.KeyEscape && action == glfw.Press {
        win.SetShouldClose(true)
    }
}

func main() {
    err := glfw.Init()
    if err != nil {
        panic(err)
    }
    defer glfw.Terminate()

    window, err := glfw.CreateWindow(640, 480, "Testing", nil, nil)
    if err != nil {
        panic(err)
    }

    window.MakeContextCurrent()
    window.SetKeyCallback(key_events)

    for !window.ShouldClose() {
        // Do OpenGL stuff.
        window.SwapBuffers()
        glfw.PollEvents()
    }
}
```

**Comment by lzap** [comment]
Filed in the core project as well: https://github.com/glfw/glfw/issues/731

**Comment by dmitshur** [comment]
Hmm. Are you referring to window chrome, or Google Chrome the browser?

Yes, the current example relies on the window manager to be able to indicate that the window should close, as can be seen on this line:

``` Go
for !window.ShouldClose() {
```

I agree with your point, a normal application should also be accessible for window managers without close buttons, but given this is a very minimal example code, its purpose is to demonstrate how to get started with GLFW... I prefer to avoid adding unrelated complexity to it. `window.SetKeyCallback(key_events)` is not needed for basic functionality, and it dilutes attention.

However, how about a simpler solution:

``` Go
for !window.ShouldClose() && window.GetKey(glfw.KeyEscape) == glfw.Release {
```

**Comment by tapir** [comment]
+1 for @shurcooL's simpler solution. I would like to keep it minimal as well.

**Comment by lzap** [comment]
Absolutely! That is much better. I asked for the same change in glfw project as well so both examples remain the same.

**Comment by dmitshur** [comment]
According to https://github.com/glfw/glfw/issues/731#issuecomment-207661794 by @linkmauve that sounds reasonable to me, this is not an issue. Closing, but let us know if there's something unexpected preventing that solution from working.
