### ISSUE TITLE
FormatUnavailable: GLX: Failed to find a suitable GLXFBConfig

### ISSUE THREAD

**Issue by EtienneBruines** [go-gl/glfw#159]
```
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: GLX: Failed to find a suitable GLXFBConfig
GLFW: Please report this bug in the Go package immediately.
```

This is my code to reproduce:

``` bash
sudo Xvfb :10 -ac &      # removing the `sudo` gives the same error
export DISPLAY=:10
go run main.go
```

Built at a Ubuntu 14.XX server (travis), but can also reproduce locally using `Linux deskserver 4.3.0-1-amd64 #1 SMP Debian 4.3.3-5 (2016-01-04) x86_64 GNU/Linux`

I have no idea what to report here.

**Comment by mewmew** [comment]
Could you provide a link to to the `game.go` source code? Or better yet, a minimal example which reproduces the issue.

**Comment by EtienneBruines** [comment]
``` go
package main

import (
    "log"
    "time"

    "github.com/go-gl/glfw/v3.1/glfw"
)

func main() {
    err := glfw.Init()
    if err != nil {
        log.Fatal(err)
    }

    glfw.WindowHint(glfw.ContextVersionMajor, 2)
    glfw.WindowHint(glfw.ContextVersionMinor, 1)
    glfw.WindowHint(glfw.Visible, glfw.False) // setting this to `glfw.True` produces the same error

    window, err := glfw.CreateWindow(1920, 1200, "Hello Bug", nil, nil)
    if err != nil {
        log.Fatal(err)
    }

    window.MakeContextCurrent()

    log.Println("Sleeping to keep the invisible window open")
    time.Sleep(time.Second * 10)
}
```

**Comment by mewmew** [comment]
Is it possible to reproduce the issue using only `glfw` and `go-gl` dependencies?

**Comment by EtienneBruines** [comment]
Trying to reproduce gave me

```
Xlib:  extension "GLX" missing on display ":11".
GLFW: An uncaught error has occurred: PlatformError: X11: RandR gamma ramp support seems broken
GLFW: Please report this bug in the Go package immediately.
Xlib:  extension "GLX" missing on display ":11".
2016/05/11 02:23:44 APIUnavailable: GLX: GLX extension not found
exit status 1
```

**Comment by EtienneBruines** [comment]
The minimized, 29 lines of code is available at https://github.com/EtienneBruines/glfw_bug

The failing build log can be viewed here: https://travis-ci.org/EtienneBruines/glfw_bug/builds/129304637

**Comment by mewmew** [comment]
Wonderful, thanks for providing a minimal reproducing example.

Does anyone with more experience in glfw care to take a look?

**Comment by dmitshur** [comment]
I don't have easy access to Linux where I can run OpenGL stuff, but since this is on Travis, I forked that reproduce case (thanks for making it) and tried a few things.

I got it to work by applying my usual Travis script setup (sourced from [here](https://github.com/goxjs/gl/blob/master/.travis.yml) and [here](https://github.com/shurcooL/Conception-go/blob/master/.travis.yml)). Can you check if that fixes your problem?

Passing build log: https://travis-ci.org/shurcooL/glfw_bug/builds/129343931

Changes: https://github.com/EtienneBruines/glfw_bug/pull/1/files

**Comment by EtienneBruines** [comment]
@shurcooL Wonderful. Apparently I was starting xvfb the wrong way, and forgot to `Give xvfb some time to start`. 

I wasn't sure if the addons supported all the libraries we're installing, but I guess that's not a problem :smile: 

Thank you very much. 

(I'm sorry to have bothered you with this; the bug told me to :laughing: )
