### ISSUE TITLE
Long pauses when switching window focus and 100% X CPU usage

### ISSUE THREAD

**Issue by davidmanzanares** [go-gl/glfw#161]
Hi,

I'm having a problem while using the library. However, I'm not sure if it is this library fault. The problem occurs in your example program (Readme.md - Usage) when running it on Ubuntu (14.04 and 16.04 have the same issue). The program runs normally fine, but, when I switch the focus to another program a long pause (~1-2 seconds) over all applications happens. I use "top" to watch the CPU usage and I notice that when I switch the focus the X system uses the 100% of the CPU.

The problem occurs even when I switch between different applications, even if none of these applications are the program (with the program running in the background). 

The computer isn't bad at all: Intel i5 2500K, Nvidia GTX 780 with Nvidia drivers...

I tried to run a C program that uses GLFW (3.1.2) and it work without problems.

I checked that this problem is not a GC pause too.

**Comment by davidmanzanares** [comment]
Note: the problem doesn't occur on Windows 7

**Comment by davidmanzanares** [comment]
I tried to reproduce the bug in other WMs and I it didn't show on KDE, XFCE nor Fluxbox. It seems that this is a Unity related problem. However, it is strange that only the go wrapper, not a plain GLFW C program, triggers the problem.

**Comment by tapir** [comment]
Can you also try with devel branch. Which has the glfw 3.2.

**Comment by davidmanzanares** [comment]
I tried to do it, but it fails. I downloaded manually the devel branch but...

```
dv@xubuntu:~/Otros/Go/src/github.com/go-gl/glfw-devel/v3.2/glfw$ go build
# github.com/go-gl/glfw-devel/v3.2/glfw
/tmp/go-build819876278/github.com/go-gl/glfw-devel/v3.2/glfw/_obj/c_glfw_linux.cgo2.o: En la función `_glfwPlatformTerminate':
./glfw/src/x11_init.c:803: referencia a `_glfwTerminateEGL' sin definir
/tmp/go-build819876278/github.com/go-gl/glfw-devel/v3.2/glfw/_obj/c_glfw_linux.cgo2.o: En la función `_glfwPlatformInit':
./glfw/src/x11_init.c:775: referencia a `_glfwInitEGL' sin definir
/tmp/go-build819876278/github.com/go-gl/glfw-devel/v3.2/glfw/_obj/c_glfw_linux.cgo2.o: En la función `_glfwPlatformCreateWindow':
./glfw/src/x11_window.c:1539: referencia a `_glfwCreateContextEGL' sin definir
./glfw/src/x11_window.c:1522: referencia a `_glfwChooseVisualEGL' sin definir
collect2: error: ld returned 1 exit status
```

**Comment by tapir** [comment]
Yeah sorry about that, turns out 3.2 is not ready yet. I'll let you know when it compiles correctly

**Comment by tapir** [comment]
Hopefully EGL should be now disabled. Can you try again?

**Comment by davidmanzanares** [comment]
Hi, I tried it again, it compiled, but the original problem persists

**Comment by tapir** [comment]
I can't reproduce this. It might be something system specific.
