### ISSUE TITLE
Add support for GLFW 3.2.

### ISSUE THREAD

**Issue by dmitshur** [go-gl/glfw#162]
GLFW 3.2 has been officially released today:

http://www.glfw.org/Version-3.2-released.html

We should add support for it, even if partially (we don't need to have support for all the new APIs right away, they can be added over time).

**Comment by dmitshur** [comment]
@tapir, I know you've started working on bindings for it on the `devel` branch. What is its status? Can we help? What's left to do?

Would you mind making a PR with it and describe the remaining tasks, so that it's possible to contribute without having to re-do the work that's already done. Would that work well?

**Comment by tapir** [comment]
I'm off from computer for a week. The changes I've made are in the README changelog. I will make a PR.

**Comment by tapir** [comment]
What needs to be done:
**Vulkan**
- glfwGetRequiredInstanceExtensions
- glfwGetInstanceProcAddress
- glfwGetPhysicalDevicePresentationSupport
- glfwCreateWindowSurface

~~**Window**~~
- ~~glfwSetWindowIcon~~

~~**Input**~~
- ~~glfwSetJoystickCallback~~

**Comment by tapir** [comment]
OK, except the Vulkan funcs it's all implemented now. The branch compiles and OpenGL cube example works. So hopefully I didn't break anything but other than that it's not tested at all.

Please review and comment.

Also what's the status on #127? What can we do to improve errors?

**Comment by tapir** [comment]
done.
