### ISSUE TITLE
GetCursorPos always return the same value

### ISSUE THREAD

**Issue by 221bytes** [go-gl/glfw#164]
Hello,

First of all, I don't have any background regarding OpenGL. I am following this tutorial
(http://www.opengl-tutorial.org/beginners-tutorials/tutorial-6-keyboard-and-mouse/)

When I try to get the cursor position by using this code :  

``` go
tmpPosx, tmpPosy = window.GetCursorPos()
window.SetCursorPos(windowWidth/2, windowHeight/2)
fmt.Fprintf(os.Stderr, "tmpPosx: %f - tmpPosy: %f\n", tmpPosx, tmpPosy)
```

I always get the same result : 
tmpPosx: 512.000000 - tmpPosy: 384.000000
tmpPosx: 512.000000 - tmpPosy: 384.000000

I use a framerate of 30 fps.
I don't think this is a problem related to the package but more probably to my code so I a looking for sample more than anything else.

PS : I know it's a newbie question ...

**Comment by dmitshur** [comment]
Can you also post the entire program, so it's easier to reproduce and offer advice?

The snippet looks roughly right.

You should also consider using [`glfw.CursorPosCallback`](https://godoc.org/github.com/go-gl/glfw/v3.1/glfw#CursorPosCallback).

**Comment by 221bytes** [comment]
glfw.CursorPosCallback. solved my problem !

Thank you for your  help !
