### ISSUE TITLE
 t

### ISSUE THREAD

**Issue by renehsz** [go-gl/glfw#165]

**Comment by tapir** [comment]
There is something wron with your gcc installation.

**Comment by ReneHSZ** [comment]
I already reinstalled gcc.

**Comment by tapir** [comment]
stddef.h is part of C standard library. If it can't be found it means you didn't install gcc properly.

**Comment by ReneHSZ** [comment]
I fixed it by copying `gcc.exe` and `gcc-ar.exe` and `gcc-nm.exe` to `%GOROOT%\pkg\tool\windows_amd64`. It took me hours to find out.

**Comment by tapir** [comment]
That's the worst possible way you can fix it. It will take minutes only if you just google how to properly install gcc on windows.

Take a look at this: http://msys2.github.io/
And don't forget to add your gcc bin directory to system PATH.

**Comment by ReneHSZ** [comment]
I know. I installed GCC exactly as described and I added the bin folder to PATH. I've tried running gcc.exe from cmd and it worked fine because there IS a gcc.exe in the system path.
