### ISSUE TITLE
error dinput

### ISSUE THREAD

**Issue by vgrabko** [go-gl/glfw#167]
Win XP

use example 

```
$  go run main.go
# github.com/go-gl/glfw/v3.2/glfw
In file included from glfw/src/internal.h:161:0,
                 from glfw/src/context.c:28,
                 from ..\github.com\go-gl\glfw\v3.2\glfw\c_glfw.go:4:
glfw/src/win32_platform.h:70:20: fatal error: dinput.h: No such file or directory
 #include <dinput.h>
                    ^
compilation terminated.
```

**Comment by dmitshur** [comment]
It looks like you're missing `dinput.h` header file, which seems to be required by GLFW on Windows:

https://github.com/glfw/glfw/blob/3.2/src/win32_platform.h#L70

According to http://linode.ogre3d.org/forums/viewtopic.php?f=2&t=81902, it looks like it's coming from DirectX SDK. Perhaps you need that?

Once we figure out what the required dependency is, we should resolve this issue by updating https://github.com/go-gl/glfw#installation.

Are you using MinGW? What version? Is it properly installed?

**Comment by v-grabko** [comment]
DirectX SDK 8.1 
demand ok http://www.glfw.org/download.html

**Comment by v-grabko** [comment]
minGW https://sourceforge.net/projects/mingw/files/latest/download?source=files

**Comment by v-grabko** [comment]
Update minGW and compiled normally. But when you run the terminal opens and immediately closes it. So it should be ?

**Comment by vgrabko** [comment]
sorry

**Comment by dmitshur** [comment]
No problem!

Did you figure out where the issue was? It'd be helpful to mention that for anyone who may find this issue later.

**Comment by vgrabko** [comment]
update MinGw to MinGw - 64 32 bit version.
