### ISSUE TITLE
`Window.SetAspectRatio` accuracy problems?

### ISSUE THREAD

**Issue by cdelorme** [go-gl/glfw#174]
I am using the glfw v3.2 bindings, and have been using a minimum size enforcement which works great so I decided to try adding aspect-ratio enforcement.

The documentation says it may break if they conflict, and I tried using some well-known dimensions such as `800x600` with `4,3` (numer/denom), as well as `1280x720` with `16,9`.

I log the dimensions on resize callbacks (same results both on window and framebuffer), and it prints `800x599`, or `1280x719`.  I tried removing the size enforcement and it continued to override the initial sizes with invalid ones.

I don't know as much C and I didn't take the time to test this behavior using the raw glfw source so I don't know if this is a bug in `glfw` itself (maybe converts to a lossy floating-point?) or the `go-gl/glfw` bindings.

If anyone knows the right way to enforce an aspect ratio programmatically I am all ears; I tried thinking on it and hit lots of barriers.

**Comment by tapir** [comment]
Here is how Go calls glfw counterpart:

``` go
func (w *Window) SetAspectRatio(numer, denom int) {
    C.glfwSetWindowAspectRatio(w.data, C.int(numer), C.int(denom))
    panicError()
}
```

Pretty straightforward. Can you try a small C example to reproduce this. It might be a bug with glfw.

**Comment by dmitshur** [comment]
The "window size callback" uses `int` units, so I wouldn't be surprised that it has no choice but to round in some cases. Perhaps the rounding logic is suboptimal?

**Comment by cdelorme** [comment]
I suck at C so it took a while to test, but I verified that using glfw directly produces the same behavior and [opened a ticket over there](https://github.com/glfw/glfw/issues/872).

Since this isn't directly a bug with the go bindings I don't know if you'd rather close this or wait for a fix.

I still haven't figured out a programmatic alternative to enforcing the aspect ratio, but once I do I'd be happy to post it here if the ticket is still open.

**Comment by tapir** [comment]
I'm closing this but you can still update us if something comes up :)

**Comment by dmitshur** [comment]
> Since this isn't directly a bug with the go bindings I don't know if you'd rather close this or wait for a fix.

We could've labeled it as "external" bug and kept open, but there's really no point in tracking this issue here since there's nothing actionable on go-gl/glfw side, aside from updating to latest GLFW when that comes out. But it'll be done anyway.

Closing in this case makes sense, since it's tracked in https://github.com/glfw/glfw/issues/872 and taken action on there.

Thanks a lot for following through with this issue @cdelorme!

**Comment by cdelorme** [comment]
Just a brief update; I tried a few other window managers and found that only openbox had this problem.  Using `xprop` I was able to verify that glfw sets the correct values via X11 window hints; my choice of window manager must have a different kind of "off-by-one" error when attempting to listen to the hints.

**Comment by cdelorme** [comment]
Just a quick update; I [opened a bug report with openbox](https://bugzilla.icculus.org/show_bug.cgi?id=6450).
