### ISSUE TITLE
Key callback called twice when holding a key

### ISSUE THREAD

**Issue by faiface** [go-gl/glfw#178]
Hello,

I'm using GLFW for Go on 64-bit Linux, Fedora 24, and I've encountered this issue. Here's my code:

```
func main() {
	err := glfw.Init()
	if err != nil {
		panic(err)
	}

	glfw.WindowHint(glfw.ContextVersionMajor, 3)
	glfw.WindowHint(glfw.ContextVersionMinor, 3)
	glfw.WindowHint(glfw.OpenGLProfile, glfw.OpenGLCoreProfile)
	glfw.WindowHint(glfw.OpenGLForwardCompatible, glfw.True)
	glfw.WindowHint(glfw.Resizable, glfw.False)

	window, err := glfw.CreateWindow(1024, 768, "GLTest", nil, nil)
	if err != nil {
		panic(err)
	}

	window.SetKeyCallback(func(_ *glfw.Window, key glfw.Key, scancode int, action glfw.Action, mods glfw.ModifierKey) {
		switch action {
		case glfw.Press:
			fmt.Println("v")
		case glfw.Release:
			fmt.Println("^")
		}
	})

	window.MakeContextCurrent()

	err = gl.Init()
	if err != nil {
		panic(err)
	}

	for !window.ShouldClose() {
		gl.ClearColor(0.2, 0.3, 0.3, 1.0)
		gl.Clear(gl.COLOR_BUFFER_BIT)

		window.SwapBuffers()
		glfw.PollEvents()
	}
}
```

What it's basically doing is that it prints 'v' when a key is pressed down and it prints '^' when a key is released.

With short presses, everything works as expected, but when I press a key for a longer time (such that glfw.Repeat events are triggered also), after releasing a key, additional Press and Release events are triggered. The output of a program then looks like this:
```
v
^
v
^
```

However, that was a single long key press.

This issue is not present when working with GLFW in C, I've tested it.

Also, I have a locked main thread and so on, so the problem's not there. Any ideas?

**Comment by faiface** [comment]
For now, the problem somehow magically disappeared after logging into Wayland (and after that it also disappeared in X11). Very weird :D. It was there nonetheless.

**Comment by tapir** [comment]
Can't reproduce on my system

**Comment by dmitshur** [comment]
Since you didn't specify, are you using the latest version of `github.com/go-gl/glfw/v3.2/glfw` package?

This sounds like it could be an external issue and it might be hard to track down.

**Comment by faiface** [comment]
I've tested it with 3.2 and 3.1. With C, I used 3.1.

It probably was some weird external issue, because as I wrote earlier, after logging into Wayland, the problem magically disappeared and doesn't show up, not even in X11.

So right now all fine, if the problem comes back, I'll tell.

**Comment by tapir** [comment]
Feel free to re-open if the problem comes back.

**Comment by faiface** [comment]
Well, the issue keeps coming back, now I've upgraded to Fedora 25, which runs GNOME on Wayland by default and the problem is present even in Wayland. I'm not sure if this is a problem with GNOME or something. Once the issue's here, but usually, after a switching between Wayland/X11 it vanishes. And the problem never pops up in GLFW with C.

**Comment by tapir** [comment]
Without being able to reproduce it on my system I'm afraid I'm not much of help. My only guess is, since nobody complained about this until now, it's probable that it's related to your system. Could you try something other than fedora? an ubuntu live usb maybe? Also (eventhough it's a far possibility) could you try with different keyboard?

**Comment by elmindreda** [comment]
It may be related to glfw/glfw#747.

**Comment by faiface** [comment]
@elmindreda It's *exactly* that, thanks! So it seems that the same problem is present in the C version. Ok, we'll have to wait until GLFW 3.3.
