### ISSUE TITLE
go get -u github.com/go-gl/glfw/v3.2/glfw fails on windows

### ISSUE THREAD

**Issue by Saurbaum** [go-gl/glfw#180]
```
go get -v -u github.com/go-gl/glfw/v3.2/glfw
github.com/go-gl/glfw (download)
github.com/go-gl/glfw/v3.2/glfw
# github.com/go-gl/glfw/v3.2/glfw
gcc: error: CreateProcess: No such file or directory
```

I've installed mingw x64.  gcc and CMake are both are in the path accessible from the cmd prompt.

**Comment by tapir** [comment]
You didn't install mingw correctly. You need to set your ENV variables and restart the computer. This is not a glfw-go bug.
