### ISSUE TITLE
Add Vulkan support

### ISSUE THREAD

**Issue by faiface** [go-gl/glfw#182]
Hi,

I know there's an older issue regarding this, but it's closed, whilst the problem is still present.

These bindings should fully support Vulkan, since the support is in GLFW3.2.

Or have I just missed something?

Thanks,
Michal Štrba

**Comment by dmitshur** [comment]
> I know there's an older issue regarding this, but it's closed

For reference, it's #154.

> whilst the problem is still present.

Can you elaborate? What problem is present?

I see:

https://godoc.org/github.com/go-gl/glfw/v3.2/glfw#VulkanSupported

Is there something missing?

**Edit:** I think you're right, PR #163 to add 3.2 support was merged, and https://github.com/go-gl/glfw/pull/163#issuecomment-226165980 says:

> The remaining Vulkan methods can be added later. I'm not even sure if they are needed for most.

And the corresponding issue #162 has more details, see https://github.com/go-gl/glfw/issues/162#issuecomment-223912137:

> What needs to be done:
> **Vulkan**
> - glfwGetRequiredInstanceExtensions
> - glfwGetInstanceProcAddress
> - glfwGetPhysicalDevicePresentationSupport
> - glfwCreateWindowSurface
> 
> ~~**Window**~~
> - ~~glfwSetWindowIcon~~
> 
> ~~**Input**~~
> - ~~glfwSetJoystickCallback~~

**Comment by faiface** [comment]
The `glfw.VulkanSupported` function always returns `false` and that has a reason. If you take a look at http://www.glfw.org/docs/latest/vulkan_guide.html, you see that it's necessary to do this before including GLFW:

```
#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>
```

Which these bindings don't do. Also, functions such as `glfwCreateWindowSurface` are not present in these bindings.

**Comment by dmitshur** [comment]
It sounds like a valid enhancement for someone interested to work on. There may be Go-binding-related challenges along the way.

**Comment by tapir** [comment]
@faiface From what I understand including the Vulkan headers (that's the only thing #define does) has nothing to do with `glfw.VulkanSupported` returning false. Looks like that flag is set in glwf.Init(). So if you get false all the time that either means you don't have a Vulkan enabled driver installed or there is a bug with GLFW.

If we add `glfwCreateWindowSurface` is that enough for starting with Vulkan?

**Comment by tapir** [comment]
Here is the related part from `glfwVulkanSupported`:
```C
#if defined(_GLFW_WIN32)
    _glfw.vk.handle = _glfw_dlopen("vulkan-1.dll");
#elif defined(_GLFW_COCOA)
    // NULL maps to RTLD_DEFAULT, which searches all loaded binaries
    _glfw.vk.handle = _glfw_dlopen(NULL);
#else
    _glfw.vk.handle = _glfw_dlopen("libvulkan.so.1");
#endif
```
Do you have one of these files?

**Comment by tapir** [comment]
https://github.com/vulkan-go/glfw

This repo is couple commits ahead of ours and it adds Vulkan support for Mac. The only differences I see is that he updated to GLFW 3.3 and added a couple build flags to link with Vulkan.

I didn't check in detail but I think the only thing (apart from couple build flags) you need to start with Vulkan is the vulkan-go package.

**Comment by tapir** [comment]
3.3 beta branch now has method called Handle() for the Window type. You can use it along with vulkan-go packages. No other Vulkan related function needs to be implemented IMHO. vulkan-go has all the functions needed.
