### ISSUE TITLE
TDM-GCC 5.1.0-2 seems to leave out strdup

### ISSUE THREAD

**Issue by mtvee** [go-gl/glfw#185]
Compiling on Windows 10 with TDM-GCC 5.1.0-2 64 bit gives me linker errors that `strdup` can't be found. I can't find anything about it via google.

I got around it my putting my own implementation of `strdup` into `...glfw/src/init.c` and got myself working again but just wanted to give a heads up.

Error output on trying to link

> github.com/go-gl/glfw/v3.2/glfw(.text): relocation target strdup not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): relocation target strdup not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): relocation target strdup not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): relocation target strdup not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: "strdup"
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: "strdup"
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: "strdup"
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: "strdup"
> exit status 2
>

**Comment by tapir** [comment]
We've had our own strdup implementation for version 3.1 but for 3.2 we've removed it because both cgo and mingw fixed the bug. I recommend updating to the latest mingw or as you did continue with using your own implementation.
