### ISSUE TITLE
will this support gomobile , any schedule?

### ISSUE THREAD

**Issue by fastfading** [go-gl/glfw#186]
it seems gomobile did not support this

gomobile build  -target=ios github.com/go-gl/glfw/v3.2/glfw
gomobile: go build -pkgdir=/Users/xxxx/git/gopath/pkg/gomobile/pkg_darwin_arm github.com/go-gl/glfw/v3.2/glfw failed: exit status 2
# github.com/go-gl/glfw/v3.2/glfw
In file included from ../src/github.com/go-gl/glfw/v3.2/glfw/c_glfw.go:4:
In file included from ./glfw/src/context.c:28:
In file included from ./glfw/src/internal.h:165:
./glfw/src/cocoa_platform.h:34:9: fatal error: 'Carbon/Carbon.h' file not found
#import <Carbon/Carbon.h>
        ^
1 error generated.

**Comment by tapir** [comment]
GLFW doesn't support mobile: https://github.com/glfw/glfw/issues/611
This is just a wrapper for the C library GLFW.

**Comment by dmitshur** [comment]
I'll paste a relevant https://github.com/glfw/glfw/issues/611#issuecomment-143641378 from that issue:

> There's a Go wrapper for GLFW at https://github.com/goxjs/glfw that currently supports desktop (OS X, Linux, Windows) and browsers (all modern browsers on any platform).
>
> It is planned to at least attempt to add support for iOS and Android there too. It's not my highest priority atm but I am curious about giving it a try sometime.

However, the current status is that it's still a very far away priority. I did start an attempt at one point, but realized it is a very significant undertaking, both in development, and in maintenance. The API of `x/mobile/app` cannot be wrapped around, so its internal functionality would have to be reimplemented and mapped to the GLFW-style API. It still helps significantly that `x/mobile` exists as a reference, but that's all it can be.

**Comment by fastfading** [comment]
thank you very much.
gomobile are much like cocos2dx (a game engine)
if there is a wrapper for both glfw(pc) and x/mobile/app(mobile)  , I think
it will support all the platform.

I have a project on pc ,  I want it could be run on mobile.
I guess, I should do the following change right?

go get -u github.com/go-gl/glfw/v3.2/glfw               -->
golang.org/x/mobile/app
go get -u github.com/go-gl/gl/v2.1/gl                   -->
golang.org/x/mobile/gl
go get -u github.com/timshannon/go-openal/openal        -->
golang.org/x/mobile/exp/audio/al


2017-03-29 3:10 GMT+08:00 Dmitri Shuralyov <notifications@github.com>:
