### ISSUE TITLE
panic while terminating

### ISSUE THREAD

**Issue by notnot** [go-gl/glfw#192]
With glfw/v3.2 i am seeing a panic when i quit my application on linux. This doesn't happen on OS X. It happens already with the simple test program. The stack trace:

onClose()
glfw3_core shutting down...
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f5a28a9f060 pc=0x7f5a28a9f060]

runtime stack:
runtime.throw(0x60db17, 0x2a)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x532a60, 0xc420053d78, 0xc4200001a0)
	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc420053d48 sp=0xc420053d08
github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwTerminate()
	github.com/go-gl/glfw/v3.2/glfw/_obj/_cgo_gotypes.go:1968 +0x41 fp=0xc420053d78 sp=0xc420053d48
github.com/go-gl/glfw/v3.2/glfw.Terminate()
	/home/jpad/gocode/extern/src/github.com/go-gl/glfw/v3.2/glfw/glfw.go:48 +0x25 fp=0xc420053d88 sp=0xc420053d78
main.main()
	/home/jpad/prog/go/jpad/src/test/glfw/glfw3.2_core/glfw3.2_core.go:273 +0xa3a fp=0xc420053f88 sp=0xc420053d88
runtime.main()
	/usr/local/go/src/runtime/proc.go:185 +0x20a fp=0xc420053fe0 sp=0xc420053f88
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420053fe8 sp=0xc420053fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
exit status 2

My version of glfw/v3.2 is already a year or so old, has this bug perhaps been fixed?

**Comment by dmitshur** [comment]
Are you using latest version of go-gl/glfw/v3.2/glfw? What version of Go? What version of Linux? What's the source code of the simple test program you tried?

**Comment by notnot** [comment]
I updated my go-gl/glfw/v3.2/glfw installation and i don't see the panic anymore :) Must have been solved in the meantime. Thanks!
