### ISSUE TITLE
`Window.SetIcon` panics with `index out of range` when passed a 0-length slice of icons

### ISSUE THREAD

**Issue by faiface** [go-gl/glfw#193]
Hi!

There's a subtle bug with the Go version of [`Window.SetIcon` method](https://godoc.org/github.com/go-gl/glfw/v3.2/glfw#Window.SetIcon). The bug occurs when passed a 0-length slice. [This line](https://github.com/go-gl/glfw/blob/master/v3.2/glfw/window.go#L360) panics in such situation, because it attempts the get the address of the first element, which is out of range.

However, the doc says it should behave otherwise:
```
If no images are specified, the window reverts to its default icon.
```

**Comment by dmitshur** [comment]
Thanks for reporting this bug @faiface.

I've made a PR #194 that fixes it. Do you want to try it out and/or review it?

**Comment by faiface** [comment]
Thanks! I'll use it when it's merged, looks correct. Passes my review ;)
