### ISSUE TITLE
arm-linux-gnueabi/bin/ld: cannot find

### ISSUE THREAD

**Issue by minhajakhterkhan199** [go-gl/glfw#197]
I am getting below error after executing go get -u github.com/go-gl/glfw/v3.1/glfw, Please advise hwo to solve this.. 

```
# github.com/go-gl/glfw/v3.1/glfw
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lGL
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lX11
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lXrandr
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lXxf86vm
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lXi
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lXcursor
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lXinerama
collect2: error: ld returned 1 exit status
```

**Comment by tapir** [comment]
it's pretty self explanatory. you should install the glfw dependencies

**Comment by dmitshur** [comment]
See the "Installation" section in the README for instructions on how to install GLFW dependencies.

https://github.com/go-gl/glfw#installation

**Comment by minhajakhterkhan199** [comment]
I have added both dependencies (libgl1-mesa-dev and xorg-dev) but still issue is not solved and I am getting same error message.. If I need to add something else then please advise.

**Comment by minhajakhterkhan199** [comment]
please advise if there is any alternative way.

**Comment by tapir** [comment]
Not that I know. You can ask @elmindreda if she has plans to implement RPi
support.

**Comment by elmindreda** [comment]
Don't currently have the time, but GLFW works well on the Pi 3 if you enable anholt's experimental OpenGL support (see `raspi-config`).

**Comment by minhajakhterkhan199** [comment]
@elmindreda I am getting below error after executing go get -u github.com/go-gl/glfw/v3.1/glfw, Please advise how to solve this.. My development machine is Ubuntu 64 & Target is Raspberry pi3 

# github.com/go-gl/glfw/v3.1/glfw
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lGL
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lX11
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lXrandr
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lXxf86vm
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lXi
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lXcursor
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lXinerama
collect2: error: ld returned 1 exit status

**Comment by tapir** [comment]
Please stop repeating yourself and start reading what you're already told. I'm closing this issue. There is enough information for OP to pursue further if he feels like.
