### ISSUE TITLE
[3.2] Build breaks with tag wayland on Linux

### ISSUE THREAD

**Issue by thomasruiz** [go-gl/glfw#198]
The build breaks with the `wayland` tag.

```
$ go get -u -tags "wayland" github.com/go-gl/glfw/v3.2/glfw
# github.com/go-gl/glfw/v3.2/glfw
In file included from ./glfw/src/internal.h:171:0,
                 from ./glfw/src/context.c:28,
                 from ../../go-gl/glfw/v3.2/glfw/c_glfw.go:4:
./glfw/src/wl_platform.h:54:66: fatal error: wayland-relative-pointer-unstable-v1-client-protocol.h: No such file or directory
 #include "wayland-relative-pointer-unstable-v1-client-protocol.h"
                                                                  ^
compilation terminated.
```

I'm using Linux (Debian).

**Comment by dmitshur** [comment]
Thanks for reporting. It seems our wayland support is not correct and needs to be fixed (either that, or you're missing some needed dependencies, which we need to document).

Best done by someone who uses Linux and Wayland.

**Comment by thomasruiz** [comment]
@shurcooL after some digging I've found a way to fix it. I still have to run 4 commands manually to make it work. Do you know if there's a way to run an external binary when the package is building?

**Comment by dmitshur** [comment]
No, but we can/should document those things in the README, under the [Installation section](https://github.com/go-gl/glfw#installation).

What are the commands?

**Comment by thomasruiz** [comment]
I created a PR (#199) containing the fix and the commands ran to make it work.

**Comment by dmitshur** [comment]
I see.

If the commands only need to be run by developers of the package (i.e., us), then it's worth considering using `go generate` directives to make them easier to re-run in the future. See https://blog.golang.org/generate about `go generate` feature. Have you considered that?

**Comment by thomasruiz** [comment]
I haven't thought about `go generate`. It might be worth to take a look at it, yes. I'll look into it later this week.

**Comment by tapir** [comment]
Merged
