### ISSUE TITLE
Is it possible to use GLFW for Go with ANGLE for better Windows support?

### ISSUE THREAD

**Issue by medvednikov** [go-gl/glfw#203]
http://angleproject.org/

Right now I can't run my application on an old Windows machine with a GPU that doesn't have OpenGL support.

**Comment by tapir** [comment]
Angle is an OpenGL ES implementation. It has nothing to do with glfw or go. I don't see why you can't use it.

**Comment by medvednikov** [comment]
@tapir that's good to hear. I don't have much experience with C++ and OpenGL, so it's not clear how to make GLFW use this implementation instead of the default one. 

According to ANGLE's docs, all you need to do is configure the build environment to have access to libEGL.lib and libGLESv2.lib. They have instructions for Visual C++. I'd be very grateful if someone could help make it work with Go.

Thanks

**Comment by tapir** [comment]
It already works with go. You should checkout go-gl/gl instead of glfw.
