### ISSUE TITLE
Panic free window destruction

### ISSUE THREAD

**Issue by fanmanpro** [go-gl/glfw#205]
I'm trying to get a nice way of destroy a GLFW window without it returning a memory or panic error.

My code currently looks like this. Where `o.window` is of type `*glfw.Window`
```
if o.window.ShouldClose() {
o.window.Destroy()
defer glfw.Terminate()
 } else if o.Active() {
...
}
```
but I'm still getting this error on the `window.ShouldClose()` line:
`panic: NotInitialized: The GLFW library is not initialized`

When I move the `glfw.Terminate()` function around, I sometimes also get it on the `glfw.PollEvents()` function call.

go env:
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/<user>/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build068015501=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```
Thanks

**Comment by dmitshur** [comment]
Did you call `glfw.Init` at the beginning if your program, before calling `window.ShouldClose`? Are you calling `glfw.Terminate` at the very end of your program, after all the other glfw calls?

`panic: NotInitialized: The GLFW library is not initialized` sounds like the kind of error you'd get if you didn't call `glfw.Init`, or if you called `glfw.Terminate` too early.

Have you looked at how the [examples](https://github.com/go-gl/example) do this?

**Comment by fanmanpro** [comment]
Sorry I forgot to mention that the game runs perfectly fine. This scenario is for when the user/player wants to exit the game manually after playing successfully.

**Comment by tapir** [comment]
Please give a minimal source code where we can replicate this error. I can't replicate it on my own setup/code.

**Comment by tapir** [comment]
@fanus can you provide a minimal code that can replicate this bug?

**Comment by fanmanpro** [comment]
Here you go:
```
package main

import (
        "github.com/go-gl/glfw/v3.2/glfw"
        "runtime"
        "time"
)

func init() {
        runtime.LockOSThread()
}

func main() {
        err := glfw.Init()
        if err != nil {
                panic(err)
        }
        defer glfw.Terminate()

        window, err := glfw.CreateWindow(640, 480, "Testing", nil, nil)
        if err != nil {
                panic(err)
        }

        window.MakeContextCurrent()
        window.SetKeyCallback(onKey)

        for !window.ShouldClose() {
                time.Sleep(100 * time.Millisecond)
                window.SwapBuffers()
                glfw.PollEvents()
        }
}

func onKey(w *glfw.Window, keycode glfw.Key, scancode int, action glfw.Action, mods glfw.ModifierKey) {
        glfw.Terminate()
}
```

When I press any key, the window disappears and the terminal returns this:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7fd3cb691420]

runtime stack:
runtime.throw(0x4e7541, 0x2a)
	/usr/lib/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4aeca0, 0xc420047f18, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc420047ee8 sp=0xc420047ea8
github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwPollEvents()
	github.com/go-gl/glfw/v3.2/glfw/_obj/_cgo_gotypes.go:1189 +0x41 fp=0xc420047f18 sp=0xc420047ee8
github.com/go-gl/glfw/v3.2/glfw.PollEvents()
	/home/fanus/Projects/go/src/github.com/go-gl/glfw/v3.2/glfw/window.go:765 +0x20 fp=0xc420047f28 sp=0xc420047f18
main.main()
	/home/fanus/Projects/go/src/github.com/autovelop/glfw-test/game.go:31 +0x11a fp=0xc420047f88 sp=0xc420047f28
runtime.main()
	/usr/lib/go/src/runtime/proc.go:185 +0x20a fp=0xc420047fe0 sp=0xc420047f88
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420047fe8 sp=0xc420047fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1
exit status 2

shell returned 1
```

**Comment by tapir** [comment]
You call glfw.Terminate twice. Once onKey is triggered and once while
deferrimg of main function. So the error you get looks logical to me. I did
not test it yet though. I'll check when I'm in front of a computer.

**Comment by fanmanpro** [comment]
Sorry forgot the defer. I removed it and the same error persists. I get the sense it is calling glfw.PollEvents() after it was terminated. Might be the issue?

**Comment by tapir** [comment]
Can you try keeping the defer and os.Exit() on onKey trigger.

**Comment by fanmanpro** [comment]
Well that does not return the error, but isn't the point to be able to keep the application running even though only the window was terminated?

**Comment by tapir** [comment]
Then you can close the window with func (*Window) SetShouldClose?
What do you want to achieve by terminating glfw and not terminating your app?

**Comment by tapir** [comment]
It's probably because it tries to call some GLFW funcs after the callback was called (like you guessed). So the error you get is expected. Not a bug. Either you can go around that with a delayed callback, or you can just close the window instead of terminating GLFW

**Comment by fanmanpro** [comment]
Ok I'm following. I got confused. I thought that restarting a game would mean terminating and re-initialising glfw but instead it is simply closing and opening the window. Thanks for the help!

**Comment by tapir** [comment]
If what you want is to reset opengl context then window.Destroy() is better then closing. But yes terminating glfw is almost never helpful except when you really want to quit the app.
