### ISSUE TITLE
An uncaught error in flatpaked application

### ISSUE THREAD

**Issue by mki1967** [go-gl/glfw#214]
When I run my flatpaked application from terminal with the command: 
`flatpak run io.github.mki1967.mki3dgame`

I have noticed the following message on the terminal:
```
GLFW: An uncaught error has occurred: PlatformError: Linux: Failed to watch for joystick connections in /dev/input: No such file or directory
GLFW: Please report this bug in the Go package immediately.
2018/02/17 13:21:31 PlatformError: Linux: Failed to open joystick device directory /dev/input: No such file or directory

```
The flatpak `io.github.mki1967.mki3dgame` is packaged according to  [io.github.mki1967.mki3dgame.json](https://github.com/flathub/io.github.mki1967.mki3dgame/blob/master/io.github.mki1967.mki3dgame.json)

It could be related to the `org.freedesktop.Platform` but I was not sure and decided to post it here because of `GLFW: ` prefix to the message.

**Comment by tapir** [comment]
This is most likely about Flatpak's sandbox and not having access to /dev/input or something. Can you check if plain C glfw throws similar error?

**Comment by mki1967** [comment]
I think you are right: This is most likely about Flatpak's sandbox. (I have reported it here because of the messege `Please report this bug in the Go package immediately`). However, I do not have much expierience with plain C glfw and I am affraid I would not be able to check it in the nearest future.

**Comment by elmindreda** [comment]
That is a known but rare issue with inotify on some Linux systems. The error message has been removed in the next release of GLFW.
