### ISSUE TITLE
Installation via `dep ensure` doesn't work

### ISSUE THREAD

**Issue by mks-m** [go-gl/glfw#221]
with `go get ...` everything works, but after converting to `dep` i'm getting this error:

```
# <gopath/src/foobar>/vendor/github.com/go-gl/glfw/v3.2/glfw
vendor/github.com/go-gl/glfw/v3.2/glfw/c_glfw.go:4:10: fatal error: 'glfw/src/context.c' file not found
#include "glfw/src/context.c"
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Gopkg.toml contains this:

```
[[constraint]]
  branch = "master"
  name = "github.com/go-gl/glfw"
```

for some reason (not sure if related) `vendor/github.com/go-gl/glfw` is missing `v3.0` folder

any ideas?

**Comment by tapir** [comment]
Check your pruning options for dep. It's pruning the C files as far as I see.

**Comment by tapir** [comment]
Also I don't know how exactly dep works but the actual Go import path is `github.com/go-gl/glfw/v3.2/glfw` not `github.com/go-gl/glfw`

**Comment by mks-m** [comment]
wow.. github issue solved within minute of reporting? that must be a record!

**Comment by mks-m** [comment]
yeah, i'm importing `v3.2/glfw` in the code, but in toml it has to be top-level path, otherwise dep errors out.

**Comment by mks-m** [comment]
i think it's detecting used packages automatically because i see in Gopkg.lock things like `packages = ["v3.2/glfw"]`

**Comment by meme** [comment]
This was marked as closed, but didn't contain any solutions. Here's what worked for me: https://github.com/golang/dep/issues/1847#issuecomment-419825487

Annoying solution though, yet it works (ensure you omit the key in the prune section)
