### ISSUE TITLE
glfw.PollEvents is slow when any key is pressed on Mac

### ISSUE THREAD

**Issue by ysmolski** [go-gl/glfw#223]
Calling glfw.PollEvents() takes 3-5 ms at peaks even without any callbacks installed on Mac.

I have discovered this problem when working with Pixel which uses glfw for the input. I have "benchmarked" wrapper [function](https://github.com/faiface/pixel/blob/master/pixelgl/input.go#L375) this way:

```
	mainthread.Call(func() {
		st := time.Now()
		glfw.PollEvents()
		fmt.Printf("%8.6f\n", time.Since(st).Seconds())
	})
```
When key is not pressed I see that it takes ~ 0.1 millisecond. But when I press any key then there are spikes up to 4-6 milliseconds. See the output from the debug hack:
```
0.004469
0.004031
0.000045
0.000087
0.003548
0.003326
0.000043
0.003076
0.000166
0.003151
0.000122
0.003320

```
Also I can reproduce it with this example: https://github.com/go-gl/example/tree/master/gl21-cube

I am not sure where to go with this. But this is a major show stopper for making games in Go. 4ms out total 16ms per frame is just too big price for one function.

How can I investigate it further?

**Comment by tapir** [comment]
Can you please test it with GLFW in C. I don't think this is related to Go at all since PollEvents method is only a single line cgo call and error check.

To see if the problem is with error check, maybe you can test the v3.3 branch and see if the problem persists. With v3.3 implicit error checks are removed.

Or you can just comment out 
```Go
func PollEvents() {
	C.glfwPollEvents()
	// panicError()
}
```
in window.go

**Comment by ysmolski** [comment]
I was able to reproduce this with glfw 3.2.1 and C using those code:
```c
  /* Loop until the user closes the window */
  while (!glfwWindowShouldClose(window))
  {
    /* Render here */
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT); // Clear the buffers

    /* Swap front and back buffers */
    glfwSwapBuffers(window);

    /* Poll for and process events */
    double seconds = glfwGetTime();
    glfwPollEvents();
    seconds = glfwGetTime() - seconds;
    printf("%.7f\n", seconds);

  }
```
I get this when I hold any key pressed:
```
0.0030390
0.0013822
0.0031350
0.0000474
0.0034653
0.0000789
0.0036935
0.0000486
0.0041693
0.0000461
0.0031637
0.0000409
0.0034748
```

**Comment by tapir** [comment]
I'm closing it for then. Thanks.
