### ISSUE TITLE
v3.0 cannot be compiled

### ISSUE THREAD

**Issue by hajimehoshi** [go-gl/glfw#227]
`go get -u` for v3.0 failed on macOS 10.14 Mojave:

```
$ GO111MODULE=off go get -u github.com/go-gl/glfw/v3.0/...
# github.com/go-gl/glfw/v3.0/glfw
ld: library not found for -lglfw3
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I don't use v3.0, but due to this problem, `go get -u github.com/go-gl/glfw/...` always fails.

**Comment by hajimehoshi** [comment]
> edit: We might actually remove it in the future as I believe no one really uses it.

+1.

**Comment by pwaller** [comment]
I'm guessing this is not of more relevance to anyone and closing it. If I am mistaken, we can reopen.
