### ISSUE TITLE
glfw doesn't draw any content initially on macOS Mojave

### ISSUE THREAD

**Issue by Noofbiz** [go-gl/glfw#228]
Due to the depreciation of OpenGL on macOS, a window created by glfw isn't drawn to until NSOpenGLContext is updated, seen [here](https://github.com/glfw/glfw/issues/1334#issuecomment-425298183). I have a workaround that calls the update [here](https://github.com/Noofbiz/glfwMojaveFix) that fixes the issue if it's called just before window.SwapBuffer(). I'm wondering if you want this integrated into this repo somewhere, and if so how would you like me to go about doing so? Thanks!

**Comment by tapir** [comment]
If it needs to be called everytime just before SwapBuffer shouldn't we put it in there? Does it need its own method?
And how will it affect people who are not on Mojave?

**Comment by elmindreda** [comment]
This was fixed with glfw/glfw@5595fa3ae60386bdb6ae4caf8f488779e3c342a3.
