### ISSUE TITLE
[Windows] A tutorial to install gcc 64 bit should be part of the readme

### ISSUE THREAD

**Issue by Tanz0rz** [go-gl/glfw#232]
I had to install GCC specifically for this library. It was quite a pain to do that and took a bit of research to get done. But then I started getting weird errors suggesting that the 32bit GCC was not the proper architecture to support the library. I then spent even more time getting the 64 bit GCC on my computer, but the install did not result in a gcc.exe, so I still couldn't get the library to compile... Installing GCC is worthy of a tutorial.

**Comment by tapir** [comment]
sorry, not gonna happen. cgo (part of go) requires gcc to work. you should learn how to setup your go environment via official channels. this is not the place for such tutorial.

https://golang.org/doc/install -> this page mentions you need gcc if you want to use cgo.

**Comment by Tanz0rz** [comment]
Maybe link to that page then? I spent a solid chunk of time trying to
figure this out.

**Comment by dmitshur** [comment]
Given how often this comes up, and how difficult it is to figure out on one's own, I agree it would be helpful to say something.

We shouldn't maintain such tutorials ourselves, but linking to some recommended resources should be okay, as long as someone is willing to maintain such a recommendation.

/cc @slimsag who I think is somewhat familiar with a functional way to install a 64-bit GCC on Windows.
