### ISSUE TITLE
Cannot install glfw on Macos

### ISSUE THREAD

**Issue by maxn0d3x** [go-gl/glfw#241]
First of all, There is no documentation and any guide to install on macos using Go.
Now, I have no idea.  Of course, I've installed X-code already. 
 **$go get -u github.com/go-gl/glfw/v3.2/glfw**

`# github.com/go-gl/glfw/v3.2/glfw
In file included from ../../workspace/Projects/Repos/_go/src/github.com/go-gl/glfw/v3.2/glfw/c_glfw.go:4:
In file included from ./glfw/src/context.c:28:
In file included from ./glfw/src/internal.h:165:
In file included from ./glfw/src/cocoa_platform.h:31:
/usr/include/dlfcn.h:40:10: fatal error: 'stdbool.h' file not found
#include <stdbool.h>
         ^~~~~~~~~~~
1 error generated.`

**Comment by tapir** [comment]
From readme


   - On macOS, you need Xcode or Command Line Tools for Xcode (xcode-select
   --install) for required headers and libraries.


Have you done this?

**Comment by maxn0d3x** [comment]
@tapir 

I've mentioned that I've already installed XCode I was an Xcode user 5 years ago :) How can I miss the readme file.. I've read the readme 100x times;; and no guide more..
So, How to install glfw on macos?? should I build glfw library using cmake on mac??

**Comment by tapir** [comment]
You've missed other things as well. This package doesnt require you to install glfw manually. It's in the readme.

**Comment by maxn0d3x** [comment]
So how can I go get glfw for golang ? 
I cannot go get glfw ; I even reinstalled go sdk completely tested in 11.5 12.0 versions

`# github.com/go-gl/glfw/v3.2/glfw In file included from ../../workspace/Projects/Repos/_go/src/github.com/go-gl/glfw/v3.2/glfw/c_glfw.go:4: In file included from ./glfw/src/context.c:28: In file included from ./glfw/src/internal.h:165: In file included from ./glfw/src/cocoa_platform.h:31: /usr/include/dlfcn.h:40:10: fatal error: 'stdbool.h' file not found #include <stdbool.h> ^~~~~~~~~~~ 1 error generated.`

**Comment by tapir** [comment]
You need stdbool.h.
That means you didn't properly setup your clang.
The problem is with your setup not with the package so I'm closing.
