### ISSUE TITLE
Support for opening a file in a mac OS bundle

### ISSUE THREAD

**Issue by andydotxyz** [go-gl/glfw#243]
I want to support opening files dragged onto the application icon.
I have set up the bundle Info.plist to respond to this - but it is failing due to the application not handing [NSApplication OpenFile:].

Can you provide a hint on how I register a delegate or provide an implementation that should allow this to happen? The GLFW code provides an application and a delegate which I cannot seem to override.

Any hints appreciated, thanks.

**Comment by tapir** [comment]
Hi, what do you mean by `The GLFW code provides an application and a delegate which I cannot seem to override.` ?
AFAIK there is no such thing and you're free to implement your own app/delegate. The question is how to do it in Go but that's not the job of GLFW.

**Comment by andydotxyz** [comment]
What I mean is this:

https://github.com/go-gl/glfw/search?utf8=%E2%9C%93&q=nsapplication&type=

The GLFW code provides an NSApplication derivative and sets an NSApplicationDelegate - of which there can only be one per application.

**Comment by tapir** [comment]
Oh I see that's part of the GLFW C code not the Go wrapper. See
github.com/glfw/glfw

**Comment by andydotxyz** [comment]
Thanks, I opened /glfw/glfw/issues/1458
