### ISSUE TITLE
Option to not use embedded GLFW source

### ISSUE THREAD

**Issue by dawidd6** [go-gl/glfw#246]
Hello,

I'm currently in the process of packaging this project for Debian
and I wonder if there is a simple way to not compile
and then statically link the embedded GLFW source?

Is it possible to link system GLFW shared library dynamically?

**Comment by tapir** [comment]
Hi, it's not possible without modifications to `c_glfw.go`, `c_glfw_linbsd.go` and `build.go` files.

**Comment by dawidd6** [comment]
Thanks for quick answer.

Is there a chance to maybe implement some `#ifdef`s in files,
so there would be a possibility to simply define a macro at build time
and then it would compile without embedded GLFW source?
I could try to produce a PR.

**Comment by tapir** [comment]
It's possible with build tags I guess. I could merge something like `go build -tags glfw-external`
PS: You can skip v3.0. It will removed at some point. If you want to send a PR please include both v3.1 and v3.2.
Also can you make it run on all platforms not just linux? Above I've said `c_glfw_linbsd.go` thinking of Debian but this one can be done in a platform agnostic way.

**Comment by tapir** [comment]
Another thing I would like to comment is that preparing a distro package for a Go lib doesn't really make much sense but if you were to make a PR I would merge it just because it would make trying out new GLFW version easier.

**Comment by pwaller** [comment]
@dawidd6 I noticed that you closed your pull request #248, so I take it your interest in this has gone or you found a workaround? Can this issue be closed?

It is legitimate to ping PRs every once in a while. The maintainers are all volunteers and generally busy doing other things.

**Comment by dawidd6** [comment]
I just don't work on this anymore. Closing the issue as well.
