### ISSUE TITLE
Not possible to import using `go mod vendor`

### ISSUE THREAD

**Issue by gustafj** [go-gl/glfw#251]
Hi, as is now its not possible to import go-gl via the vendor directory using `go mod vendor`.

The reason is that `go mod vendor` prunes all directories with `.c` files that does not have a companion `.go` file.
This results in failed builds due to lacking `.c` sources, e.g. `vendor/github.com/go-gl/glfw/v3.2/glfw/c_glfw.go:4:10: fatal error: 'glfw/src/context.c' file not found`

This is expected behavior on the `go mod vendor` part (see https://github.com/golang/go/wiki/Modules#some-needed-files-may-not-be-present-in-populated-vendor-directory) but basically means that go-gl is not possible to vendor.

Would it be possible to solve this by bundling a `dummy.go` file in the affected directories?

**Comment by pwaller** [comment]
Hi! Thanks for reporting this. Your solution of `dummy.go` sounds fine to me. PR welcome.

**Comment by pwaller** [comment]
@gustafj I've submitted a fix for you in #258 - please take a look and let me know if it fixes your issues or not.

**Comment by rbrownrigg** [comment]
Can the associated pull request be merged and this issue closed out?  I've stumbled across this issue too in the context of modules/vendoring.

Thanks

**Comment by pwaller** [comment]
@rbrownrigg if you test it and leave a message on the PR saying it solves the problem for you, I'll merge it.

**Comment by gustafj** [comment]
Unfortunately it don't :cry:, see my comment in the PR.
