### ISSUE TITLE
Error Mac OSX 10.13.6

### ISSUE THREAD

**Issue by alexelisenko** [go-gl/glfw#252]
I am using go-flutter to build a Mac application, and for the most part it works, but on 10.13.6, I get the following error:

```
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: NSGL: Failed to find a suitable pixel format
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: NSGL: Failed to find a suitable pixel format
 
goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.2/glfw.acceptError(0xc000097d28, 0x2, 0x2, 0x0, 0x0)
    /Users/alex/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/error.go:178 +0x203
github.com/go-gl/glfw/v3.2/glfw.CreateWindow(0x1b8, 0x2d0, 0x41700d9, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
```

The main executable was built on 10.14.5.

**Comment by alexelisenko** [comment]
This error seems to be related to:

`glfwWindowHint(GLFW_STENCIL_BITS, 8);`

Can anyone point me in the right direction to how to set this?

**Comment by pchampio** [comment]
This issue can be closed, @alexelisenko was running the glfw app in a Virtual machine which didn't fully supported OpenGL drivers.
