### ISSUE TITLE
request: want CocoaWindow to return uintptr

### ISSUE THREAD

**Issue by hajimehoshi** [go-gl/glfw#259]
https://github.com/go-gl/glfw/blob/e5ec43523f6ff18bd5fc260244ea6ff9d5d6bc96/v3.3/glfw/native_darwin.go#L29

In 3.2, `CocoaWindow` returned `uintptr` but in 3.3, this returns `unsafe.Poitner`. As `unsafe.Pointer` means a pointer that GC can collect, `uintptr` should be more natural.

@pchampio What do you think? Is there a strong reason to use `unsafe.Pointer` here?

**Comment by pchampio** [comment]
https://github.com/go-gl/glfw/issues/230
https://github.com/go-gl/gl/issues/113#issuecomment-431845002

**Comment by hajimehoshi** [comment]
Ah, I forgot that completely :-) Thanks!
