### ISSUE TITLE
Warnings on macOS

### ISSUE THREAD

**Issue by hajimehoshi** [go-gl/glfw#260]
I used `github.com/go-gl/glfw/v3.3/glfw v0.0.0-20191124195120-e5ec43523f6f` and found these warnings:

```
# github.com/go-gl/glfw/v3.3/glfw
In file included from ../go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20191124195120-e5ec43523f6f/c_glfw_darwin.go:8:
../go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20191124195120-e5ec43523f6f/glfw/src/cocoa_window.m:819:9: warning: multiple methods named 'center' found [-Wobjc-multiple-method-names]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCollectionViewCompositionalLayout.h:601:19: note: using
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:312:1: note: also found
```

**Comment by pchampio** [comment]
Ever since my v3.3 PR glfw/glfw@3.3-stable has evolved, this has been recently fixed by the glfw/glfw team.
Fixed in https://github.com/glfw/glfw/tree/3.3-stable
Commit: https://github.com/glfw/glfw/commit/b3c2023ebc40b9003c7942eb4549358402be5d92#diff-9e4ea39e73b983e33beb8ef73c8fb558

**Comment by hajimehoshi** [comment]
Thanks. I was wondering if it'd be possible to cherry-pick the change.

Actually, I've requested cherry-picking from GLFW to go-gl/GLFW and that was accepted: https://github.com/go-gl/glfw/issues/225
