### ISSUE TITLE
glfw is not seen by go tools in VS Code

### ISSUE THREAD

**Issue by zergon321** [go-gl/glfw#265]
Default **Go** tools which provide autocompletion and docs for **VS Code** don't work with `glfw` functions. "Go to definition" doesn't work as well. Error detection works though. How to fix autompletion and docs? I use `gogetdocs` for docs and `go.useLanguageServer` is set to `true`.

**Comment by zergon321** [comment]
Wow. It turns out that I shouldn't have used **Go Language Server** for autocompleteion and docs while working with `glfw`. It was just enough to set `go.useUseLanguageServer` to false. I hope this will help someone else.

**Comment by dmitshur** [comment]
> It turns out that I shouldn't have used **Go Language Server** for autocompleteion and docs while working with `glfw`.

From reading https://github.com/golang/tools/tree/master/gopls#issues, https://github.com/golang/tools/blob/master/gopls/doc/status.md#known-issues, golang/go#35720, and golang/go#33030, I believe it should work as of gopls v0.3.0 (released Jan 31, 2020) and newer. /cc @heschik

Can you please try again with the [latest release version of gopls](https://github.com/golang/tools/tree/master/gopls#using), and if it still doesn't work, [file an issue](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#steps) in the Go issue tracker with more details? Thanks.
