### ISSUE TITLE
Setting glfw.FocusOnShow / glfw.Focused false doesn't have any effects on Windows

### ISSUE THREAD

**Issue by hajimehoshi** [go-gl/glfw#267]
```diff
$ git diff
diff --git a/gl21-cube/cube.go b/gl21-cube/cube.go
index 1b4bbb0..ef29075 100644
--- a/gl21-cube/cube.go
+++ b/gl21-cube/cube.go
@@ -40,6 +40,8 @@ func main() {
        glfw.WindowHint(glfw.Resizable, glfw.False)
        glfw.WindowHint(glfw.ContextVersionMajor, 2)
        glfw.WindowHint(glfw.ContextVersionMinor, 1)
+       glfw.WindowHint(glfw.FocusOnShow, glfw.False)
+       glfw.WindowHint(glfw.Focused, glfw.False)
        window, err := glfw.CreateWindow(width, height, "Cube", nil, nil)
        if err != nil {
                panic(err)
```

I'm not sure this is a bug. I've not tested C version yet.

**Comment by pwaller** [comment]
Please report back with C reproducer if you can. If it manifests there, please file an issue upstream.

**Comment by hajimehoshi** [comment]
Sure. It looks a little difficult to build C GLFW on Windows though...

**Comment by rubensayshi** [comment]
@hajimehoshi I'm having the same issue on Ubuntu, what was the misunderstanding?

I was expecting you your code snippet to pop open a window without stealing focus from w/e had focus before, but it always steals focus

**Comment by hajimehoshi** [comment]
Sorry but I forgot the situation (probably I couldn't reproduce the case).

If you have the same issue, please create a new issue, or create an issue at glfw/glfw. Thanks,
