### ISSUE TITLE
How to create a headless display?

### ISSUE THREAD

**Issue by gmlewis** [go-gl/glfw#275]
Context: https://github.com/gmlewis/irmf-slicer/blob/master/irmf/slicer.go#L73-L80

I'm trying to create a stand-alone program that creates an OpenGL headless display and renders into it and saves the results.

When I add this line to the program:

```
glfw.WindowHint(glfw.ContextCreationAPI, glfw.OSMesaContextAPI)
```

it fails on Linux with the error:

```
CreateWindow(640,640): VersionUnavailable: OSMesa: Forward-compatible contexts not supported
```

I thought this might work because on this page: https://www.glfw.org/docs/latest/compile.html#compile_deps
it says:

> `_GLFW_OSMESA` to use the OSMesa API (headless and non-interactive)

Any ideas what I'm doing wrong?

Thank you!

**Comment by golightlyb** [comment]
Quick suggestion if you haven't tried it already, change the line above:
 `glfw.WindowHint(glfw.OpenGLForwardCompatible, glfw.True)` <-- change this to False

**Comment by gmlewis** [comment]
> Quick suggestion if you haven't tried it already, change the line above:
> `glfw.WindowHint(glfw.OpenGLForwardCompatible, glfw.True)` <-- change this to False

Thank you, @golightlyb , but unfortunately, that gives me this error instead:

```
2020/03/13 07:27:20 CreateWindow(640,640): VersionUnavailable: OSMesa: Failed to create context
```

(I tried this using both `"github.com/go-gl/gl/v4.1-core/gl"` and `"github.com/go-gl/gl/v4.6-core/gl"` imports and get the same error message.)

**Comment by gmlewis** [comment]
Doh, it turns out the solution is easy.  I needed to add this line instead:

```
	glfw.WindowHint(glfw.Visible, glfw.False)
```

...and then it worked.  Thanks, everyone... sorry for the noise.
