### ISSUE TITLE
v3.3/glfw: Panic when calling GetClipboardString from an empty clipboard

### ISSUE THREAD

**Issue by spatocode** [go-gl/glfw#276]
Calling GetClipboardString from an empty clipboard panics with error:

GLFW: An invalid error was not accepted by the caller: FormatUnavailable: X11: Failed to convert selection to string

**Comment by andydotxyz** [comment]
This was originally reported in Fyne: fyne-io/fyne#743.
The documentation indicates that a format error should not cause a panic, but it seems to anyway.
We have installed an error handler when calling clipboard or pollevent methods (as this can originate from either)
