### ISSUE TITLE
Menus on macOS Catalina are not usable after initial launch.

### ISSUE THREAD

**Issue by andydotxyz** [go-gl/glfw#279]
When launching an app on macOS Catalina the menus cannot be interacted with.

Bringing another application to the front and then switching back makes the app usable.

# To reproduce

* Using the code from this project's README simply `go run main.go` on macOS Catalina
* Try to interact with the menu - no response
* Change app and change back
* Menus work

Originally reported as fyne-io/fyne#505.

**Comment by andydotxyz** [comment]
I guess this is a duplicate of the upstream issue glfw/glfw#1648

**Comment by pwaller** [comment]
I guess this isn't an issue in go-gl/glfw. If it persists after a fix lands upstream, we can reopen this issue. Please also report back when the upstream issue is fixed if you can. Thanks!

**Comment by jphsd** [comment]
Looks like the upstream issue was [fixed](https://github.com/glfw/glfw/commit/cdc3b71a90434fae3255edf4f152da0971733499)?

**Comment by andydotxyz** [comment]
It was, but I think they are testing a different fix that is more backwards compatible.
