### ISSUE TITLE
Paste image from system into glfw window will cause crash.

### ISSUE THREAD

**Issue by AllenDang** [go-gl/glfw#281]
GLFW version: glfw/v3.3/glfw@v0.0.0-20200222043503-6f7a984d4dc4
go version: go version go1.14.2 darwin/amd64
OS: MacOS 10.15.4 (19E287)

Repo steps:
1. Cmd+Ctrl + Shift + 4 (MacOS hotkey to capture screen region and copy to clipboard).
2. Cmd+v in GLFW window.

Error logs:
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: Cocoa: Failed to retrieve string from pasteboard
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: Cocoa: Failed to retrieve string from pasteboard

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0x0, 0x0, 0x0, 0x0, 0x6124680)
        /Users/allendang/Documents/Gocode/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200222043503-6f7a984d4dc4/error.go:178 +0x201
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
        /Users/allendang/Documents/Gocode/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200222043503-6f7a984d4dc4/error.go:185
github.com/go-gl/glfw/v3.3/glfw.(*Window).GetSize(0xc0004a6000, 0x6124680, 0x0)
        /Users/allendang/Documents/Gocode/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200222043503-6f7a984d4dc4/window.go:481 +0x88

**Comment by pwaller** [comment]
Was this fixed by #282, or is it a distinct problem? (cc @pchampio)

Sorry, I don't have a OSX to check.

**Comment by pchampio** [comment]
Yes, this should be fixed by #282

**Comment by pwaller** [comment]
Closing under the assumption it's fixed. If it isn't, please report back and we'll reopen.
