### ISSUE TITLE
Hiding window crashes in OpenBox 

### ISSUE THREAD

**Issue by andydotxyz** [go-gl/glfw#289]
A simple GLFW window that is opened and then hidden will crash the application in OpenBox, with the following error:

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x2005de
  Serial number of failed request:  270
  Current serial number in output stream:  270
exit status 1
```

**Comment by tapir** [comment]
Can you try with plain GLFW in C. Looks like an upstream issue.

**Comment by andydotxyz** [comment]
Closing out as nobody has reported it recently so could have been fixed in any number of changes :)

**Comment by Jacalz** [comment]
Yeah, most likely a bug somewhere else in the stack and not directly in the Go bindings.
