### ISSUE TITLE
Override Redirect

### ISSUE THREAD

**Issue by hen6003** [go-gl/glfw#295]
how would i enable Override Redirect for my window?

**Comment by pwaller** [comment]
This is the Go bindings project for glfw. And I don't know what you're asking for. I found this comment though in the glfw sources, which suggests you're trying to make a fullscreen window? Could you elaborate on what you're trying to do?

https://github.com/glfw/glfw/blob/0ef149c8f2451fbc8e866834675a075cfc295b6c/src/x11_window.c#L314-L331
