### ISSUE TITLE
v3.3/glfw: memory leak 

### ISSUE THREAD

**Issue by SeanTolstoyevski** [go-gl/glfw#297]
Go version: 1.15 64bit
mingw-w64: GCC 10.2.0
OS: windows 10 64bit

## Steps to reproduce

1. `go get -u github.com/go-gl/glfw/v3.3/glfw`
2. Copy the example from readme to a go file.
3. compile: `go build -ldflags "-s -w -H=windowsgui" .

## Result

If you open Taskmanager and wait, you will see that the ram usage starts to increase without anything. I've had an increase of 1-1.2MB in 90 seconds.

I thought this was due to go's runtime. So I tested it for a long time. Looks like there is a memory leak.
This situation does not change.

**Comment by tapir** [comment]
Can't seem to reproduce this.
I see that the memory consumption increases a little bit with time but then it's pretty much stable at 27MB for me. I also see GC is kicked in periodically. Might be due to our error handling code producing a little garbage -which basically runs in all functions-

**Comment by SeanTolstoyevski** [comment]
Yes, if you don't say memory leak for a software to produce 1.2-1.5 mb 1-2  minute without doing anything. This may not be a memory leak.
I will test this case with C++ with the same version of OpenGL.

**Comment by tapir** [comment]
You seem to miss the fact that Go is garbage collected
