### ISSUE TITLE
Enter Chinese in full screen

### ISSUE THREAD

**Issue by leielyq** [go-gl/glfw#300]
I can’t see the preview when I enter Chinese in full screen

**Comment by dmitshur** [comment]
This issue tracker is for the Go bindings to GLFW. Does the problem also occur upstream, in [GLFW itself](https://www.glfw.org/)?

**Comment by pwaller** [comment]
Thanks for reporting an issue, however, there is not enough information in this bug report for us to take action to fix a bug.

Closing for now, but if you want to provide more information such that this is actionable, we will happily reopen.

As @dmitshur points out, it seems this is also unlikely to be an issue in the bindings, rather an upstream issue.
