### ISSUE TITLE
Bump GLFW 3.3.3 to support Apple Silicon (Apple M1)

### ISSUE THREAD

**Issue by ipfans** [go-gl/glfw#303]
As https://github.com/glfw/glfw/pull/1833, only GLFW 3.3.3 can works fine with Apple Silicon. So maybe we should upgrade bundled GLFW version to 3.3.3 to support Apple Silicon.

**Comment by dmitshur** [comment]
Sure, but I understand that 3.3.3 hasn’t been released yet.

**Comment by ipfans** [comment]
@dmitshur Yes, GLFW still 3.3.2, so we can open this issue until it release.

**Comment by wilkesreid** [comment]
GLFW 3.3.3 was released on February 23

**Comment by pwaller** [comment]
Paging anyone interested to contribute to assist with #271 (with testing/review), which is a PR containing a script for updating the sources. It should work for upgrading to v3.3.3 trivially in principle.

**Comment by pwaller** [comment]
If anyone wants to give this a go, update https://github.com/go-gl/glfw/blob/06ea97f0c265e8f81bc3b76ab51a5e4d66e87c23/v3.3/glfw/GLFW_C_REVISION.txt to be an updated revision from upstream and run scripts/grab-upstream.sh from #271.

**Comment by IAmJSD** [comment]
> If anyone wants to give this a go, update https://github.com/go-gl/glfw/blob/06ea97f0c265e8f81bc3b76ab51a5e4d66e87c23/v3.3/glfw/GLFW_C_REVISION.txt to be an updated revision from upstream and run scripts/grab-upstream.sh from #271.

I tried running that script after bumping the text file, and I get a lot of `wayland-scanner: command not found`. I take it by this that I am not supposed to run it from macOS, so should what env should I be using instead?

**Comment by pwaller** [comment]
Ah, yes, this will only work from linux with wayland scanner involved. Apologies. I've just run the script and pushed a branch, please try this: https://github.com/go-gl/glfw/tree/update-3.3.3

**Comment by IAmJSD** [comment]
> Ah, yes, this will only work from linux with wayland scanner involved. Apologies. I've just run the script and pushed a branch, please try this: https://github.com/go-gl/glfw/tree/update-3.3.3

Just bumped a project to that, LGTM

**Comment by pwaller** [comment]
If you're hot off the mark, make sure you have have master as of now to include 0c4de960255c8c5d7b2b1a69984a3d723cdfaea3. Otherwise it's possible a build with a pre-existing go build cache will not reflect the update, because go's build cache invalidation until then did not take into account changes to only C files.
