### ISSUE TITLE
"GLFW: Please report this bug in the Go package immediately."

### ISSUE THREAD

**Issue by benkasminbullock** [go-gl/glfw#317]
Trying to build https://github.com/danfragoso/thdwb, got this message:
````
# github.com/go-gl/glfw/v3.3/glfw
In file included from /home/ben/software/golib/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/native_linbsd.go:10:
In file included from /home/ben/software/golib/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/glfw/include/GLFW/glfw3native.h:114:
In file included from /usr/local/include/GL/glx.h:32:
/usr/local/include/GL/gl.h:56:11: warning: 'GLAPIENTRY' macro redefined [-Wmacro-redefined]
/home/ben/software/golib/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/glfw/include/GLFW/glfw3.h:5894:10: note: previous definition is here
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: GLX: Failed to find a suitable GLXFBConfig
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: GLX: Failed to find a suitable GLXFBConfig

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0x318c5ed0, 0x2, 0x2, 0x0, 0x0)
	/home/ben/software/golib/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/error.go:178 +0x1ab
github.com/go-gl/glfw/v3.3/glfw.CreateWindow(0x384, 0x258, 0x4d426f, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ben/software/golib/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/window.go:350 +0x149
github.com/danfragoso/thdwb/mustard.CreateNewWindow(0x4d426f, 0x5, 0x384, 0x258, 0x1, 0x0)
	/usr/home/ben/software/thdwb/mustard/window.go:23 +0x47
main.main()
	/usr/home/ben/software/thdwb/browser/main.go:46 +0x254
exit status 2
*** Error code 1

Stop.
make: stopped in /usr/home/ben/software/thdwb
````

**Comment by tapir** [comment]
Are you on a headless system?

**Comment by benkasminbullock** [comment]
> Are you on a headless system?

Sorry but I don't know what that means.

**Comment by tapir** [comment]
If there is no X server running GLX would fail. It looks like it can't get a framebuffer going on.

**Comment by benkasminbullock** [comment]
On Fri, 23 Apr 2021 at 00:55, Coşku Baş ***@***.***> wrote:

> If there is no X server running GLX would fail. It looks like it can't get
> a framebuffer going on.
>

There's no X server running on this computer.

**Comment by tapir** [comment]
You should read README for the needed packages which I'm sure would also install X server along. If you don't want it then you can try xvfb which is a virtual framebuffer implementation of X (without display) but then you're own your own.

**Comment by benkasminbullock** [comment]
On Fri, 23 Apr 2021 at 06:36, Coşku Baş ***@***.***> wrote:

> You should read README for the needed packages which I'm sure would also
> install X server along. If you don't want it then you can try xvfb which is
> a virtual framebuffer implementation of X (without display) but then you're
> own your own.
>
The only thing I've read is the message issued by your software, which is
the title of this bug report.

I'm not interested in reading README or trying xvfb.

**Comment by tapir** [comment]
Feel free to not open an issue next time you see such a message then.
