### ISSUE TITLE
Cross-compiling?

### ISSUE THREAD

**Issue by eboatwright** [go-gl/glfw#331]
How do I cross compile from MacOS to Windows?
I've tried the standard:
GOOS=windows GOARCH=amd64 go build -o bin/{MODULE}.exe github.com/eboatwright/{MODULE}
but it returns:
./main.go:16:9: undefined: glfw.Init
./main.go:20:8: undefined: glfw.Terminate
./main.go:22:17: undefined: glfw.CreateWindow
./main.go:31:3: undefined: glfw.PollEvents

**Comment by gucio321** [comment]
hi,  You probably need mingw installed. I'm doing so on linux with the following:
`CGO_ENABLED="1" GOOS="windows"  CC="/usr/bin/x86_64-w64-mingw32-gcc" CXX="/usr/bin/x86_64-w64-mingw32-c++" go build -o oug.exe .`
on macos it should be simillar.

**Comment by eboatwright** [comment]
Ok cool! Thanks for your help! 😄
