### ISSUE TITLE
panic: FormatUnavailable: NSGL: Failed to find a suitable pixel format

### ISSUE THREAD

**Issue by amo13** [go-gl/glfw#335]
Reporting this because the error message asks me to:
```
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: NSGL: Failed to find a suitable pixel format
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: NSGL: Failed to find a suitable pixel format
goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0xc0004ffb08, 0x2, 0x53a9d80})
/Users/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210727001814-0db043d8d5be/error.go:178 +0x177
github.com/go-gl/glfw/v3.3/glfw.CreateWindow(0xc0004a6000, 0xc0000002e8, {0x498e4c4, 0x40859b0}, 0x0, 0x0)
/Users/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210727001814-0db043d8d5be/window.go:350 +0x170
fyne.io/fyne/v2/internal/driver/glfw.(*window).create.func1()
/Users/runner/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/window.go:1427 +0x131
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc0000c6b90)
/Users/runner/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/loop.go:104 +0x197
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc0004a6000)
/Users/runner/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/driver.go:83 +0x30
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0xc0004a6000)
/Users/runner/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/window.go:461 +0x2f
main.main()
```

I have tried running an app using the [fyne](https://github.com/fyne-io/fyne) gui toolkit on a virtual hackintosh (for testing purposes) that I have set up [using KVM](https://github.com/foxlet/macOS-Simple-KVM) on my linux pc.

Feel free to flag it with `#wont-fix` and close this issue if this corner case is way too corner to get any real attention ;)

**Comment by Jacalz** [comment]
Does your virtual machine have hardware acceleration supported? I know that it has been a common issue for people using virtual machines with Fyne.

**Comment by amo13** [comment]
Ah, I see. It very well possible that I simply didn't setup GPU passthrough.
Can't verify any more since I needed to delete this VM, sorry.

**Comment by Jacalz** [comment]
No worries. Was just passing by and hoped to help you given that it was Fyne related. I would have gotten to it faster if you had opened it in the issue tracker there ;)

**Comment by amo13** [comment]
Thanks, and no worries neither.
And thank you for being part of the by far most helpful developers I have encountered on the web. The existence of fyne was one reason why I chose to learn go and I was absolutely amazed by all the help I already have gotten with fyne so far.
Cheers to you and the team.

**Comment by Jacalz** [comment]
I'll bring that along. Thanks for the kind words :)
